import "server-only";
import { buildPhase2Predictions } from "./phase2PredictionEngine";

const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const finite=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const norm=(v,min,max,f=.5)=>{const n=finite(v);return n===null?f:clamp((n-min)/(max-min),0,1);};
export function mapDailyEntry(row){return {...row,boat_no:Number(row.boat_no??row.teiban),racer_name:String(row.racer_name??row.shimei??"").replace(/\u3000/g," ").replace(/\s+/g," ").trim(),national_win_rate:finite(row.national_win_rate),local_win_rate:finite(row.local_win_rate),motor_2_rate:finite(row.motor_top2_rate??row.motor_2_rate),boat_2_rate:finite(row.race_boat_top2_rate??row.boat_2_rate),average_st:finite(row.average_st),exhibition_time:finite(row.official_exhibition_time??row.exhibition_time??row.api_exhibition_time),exhibition_st:finite(row.official_exhibition_st??row.exhibition_st??row.api_exhibition_st),official_lap:finite(row.official_lap??row.lap_time),official_turn:finite(row.official_turn??row.turn_time),official_straight:finite(row.official_straight??row.straight_time)};}
function female(e){if(Number(e.sex_code)===2)return true;const v=`${e.gender||""} ${e.gender_code||""}`.toLowerCase();return v.includes("女")||v.includes("female")||/(^|\s)(2|f)(\s|$)/.test(v);}
function base(e){const st=finite(e.average_st);return norm(e.national_win_rate,2.5,8)*.28+norm(e.local_win_rate,2.5,8)*.18+norm(e.motor_2_rate,20,55)*.18+norm(e.boat_2_rate,20,55)*.08+(st===null?.5:clamp((.24-st)/.16,0,1))*.18+(Number(e.boat_no)===1?1:clamp(.76-(Number(e.boat_no)-2)*.10,.2,.76))*.10;}
function exhibition(e,entries){const vals=entries.map(x=>finite(x.exhibition_time)).filter(x=>x!==null);const n=finite(e.exhibition_time);if(n===null||!vals.length)return .5;const min=Math.min(...vals),max=Math.max(...vals);return max===min?.5:clamp((max-n)/(max-min),0,1);}
function boatProbability(entries,boatNo,live){const weights=entries.map(e=>{const p=base(e)*(live?.64:1)+(live?exhibition(e,entries)*.36:0);return {n:Number(e.boat_no),w:Math.exp((p+(Number(e.boat_no)===1?.14:0))*4.4)};});const total=weights.reduce((s,x)=>s+x.w,0),t=weights.find(x=>x.n===boatNo);return total&&t?t.w/total:0;}
function mark(prob){return prob>=.8?"◎":prob>=.65?"○":prob>=.5?"▲":prob>=.35?"△":"見";}
function bets(pred){return Array.isArray(pred?.bet_json)?pred.bet_json.map(x=>x?.bet).filter(Boolean).join(" / "):"";}
export function evaluateDailyRace({event,entries,character,timing}){if(entries.length!==6)return {eligible:false,mark:"見",confidence:"",main:"",bet:"",comment:"6艇データが揃っていません"};const live=timing==="after_exhibition";if(character==="ichika"){const built=buildPhase2Predictions({event,entries});const p=live?(built.livePrediction??built.previousPrediction):built.previousPrediction;if(!p)return {eligible:true,mark:"見",confidence:"",main:"",bet:"",comment:"イン本命条件に届かないため見送り"};const prob=clamp(Number(p.score||0)/100,0,1);return {eligible:true,mark:mark(prob),confidence:`${(prob*100).toFixed(1)}%`,main:"1号艇",bet:bets(p),comment:p.comment_text||"イン逃げ評価"};}
 if(character==="hatsune"){if(!entries.every(female))return {eligible:false,mark:"見",confidence:"",main:"",bet:"",comment:"女子戦ではないため対象外"};const built=buildPhase2Predictions({event,entries});const p=live?(built.livePrediction??built.previousPrediction):built.previousPrediction;const escape=clamp(Number(p?.score||0)/100,0,1),risk=1-escape;const prob=Math.max(escape,risk),main=escape>=risk?"1号艇":"イン不安";return {eligible:true,mark:mark(prob),confidence:`${(prob*100).toFixed(1)}%`,main,bet:escape>=risk?bets(p):"",comment:escape>=risk?"女子戦のイン優勢度を評価":"女子戦のイン不安度が高く、波乱警戒"};}
 const prob=boatProbability(entries,5,live);return {eligible:true,mark:mark(prob),confidence:`${(prob*100).toFixed(1)}%`,main:prob>=.35?"5号艇":"",bet:"",comment:prob>=.35?"5号艇の1着期待を穴候補として評価":"5号艇の1着期待は低め。見送り候補"};}
