import Link from "next/link";
import {formatNumber,formatSyncedAt,getCourseName,getRaceDetail,normalizeCourseCode,normalizeDate,normalizeRaceNo,normalizeRacerName} from "../../../lib/boatstrikersLive";
import s from "../../live.module.css";
export const dynamic="force-dynamic";
const tabs=new Set(["basic","previous","live"]);
function Tab({active,href,icon,small,title,className=""}){return <Link scroll={false} href={href} className={`${s.tab} ${className} ${active?s.tabActive:""}`}><span>{icon}</span><div><small>{small}</small><strong>{title}</strong></div></Link>}
function Entry({e}){const grade=String(e.racer_class||"").toUpperCase();return <article className={s.entryCard}><div className={s.entryTop}><span className={`${s.boat} ${s.largeBoat} ${s[`boat${e.boat_no}`]}`}>{e.boat_no}</span><div className={s.entryName}><span className={`${s.classBadge} ${grade==="A1"?s.a1:grade==="A2"?s.a2:""}`}>{grade||"-"}</span><h3>{normalizeRacerName(e.racer_name)}</h3><p>登録番号 {e.racer_registration_no||"-"}</p></div></div><div className={s.stats}><div><span>全国勝率</span><strong>{formatNumber(e.national_win_rate)}</strong></div><div><span>当地勝率</span><strong>{formatNumber(e.local_win_rate)}</strong></div><div><span>展示</span><strong>{formatNumber(e.exhibition_time)}</strong></div><div><span>展示ST</span><strong>{formatNumber(e.exhibition_st)}</strong></div></div><div className={s.extra}><div><span>モーター</span><strong>{e.motor_no??"-"}</strong></div><div><span>モーター2連率</span><strong>{formatNumber(e.motor_2_rate)}%</strong></div><div><span>ボート</span><strong>{e.boat_machine_no??"-"}</strong></div><div><span>ボート2連率</span><strong>{formatNumber(e.boat_2_rate)}%</strong></div></div><div className={s.series}><span>今節成績</span><strong>{e.current_series_results||"-"}</strong></div></article>}
export default async function Page({params,searchParams}){
 const p=await params,q=await searchParams,code=normalizeCourseCode(p.courseCode),raceNo=normalizeRaceNo(p.raceNo),date=normalizeDate(q?.date),tab=tabs.has(q?.tab)?q.tab:"basic";
 if(!code||!raceNo)return <main className={s.page}><section className={s.content}><div className={s.error}><span>⚠️</span><h2>URLが不正です</h2></div></section></main>;
 let event=null,entries=[],err=null;try{({event,entries}=await getRaceDetail(date,code,raceNo));}catch(e){console.error(e);err=e.message;} const name=getCourseName(code),base=`/races/${String(code).padStart(2,"0")}/${raceNo}`;
 return <main className={s.page}><header className={s.hero}><div className={s.inner}><div className={s.top}><Link className={s.pill} href={`/races/${String(code).padStart(2,"0")}?date=${date}`}>← {name}レース一覧</Link><Link className={s.pill} href={`/races?date=${date}`}>開催場</Link></div><div className={s.title}><div className={s.raceNo}><strong>{raceNo}</strong>R</div><div><p className={s.eyebrow}>BOATSTRIKERS RACE DETAIL</p><h1>{name} {raceNo}R</h1><p className={s.desc}>基本出走表・前日版新聞・直前版</p><div className={s.metaRow}><span className={s.meta}>{date}</span><span className={s.meta}>{event?.race_status==="exhibition"?"展示公開":"出走表公開"}</span><span className={s.meta}>同期 {formatSyncedAt(event?.synced_at)}</span></div></div></div></div></header>
 <section className={s.content}><nav className={s.tabs}><Tab active={tab==="basic"} href={`${base}?date=${date}&tab=basic`} icon="📋" small="実データ" title="出走表"/><Tab active={tab==="previous"} href={`${base}?date=${date}&tab=previous`} icon="📰" small="AI予想" title="前日版" className={s.previous}/><Tab active={tab==="live"} href={`${base}?date=${date}&tab=live`} icon="⚡" small="展示後" title="直前版" className={s.liveTab}/></nav>
 {err?<div className={`${s.error} ${s.panel}`}><span>⚠️</span><h2>取得できませんでした</h2><p>{err}</p></div>:!event||!entries.length?<div className={`${s.empty} ${s.panel}`}><span>🚤</span><h2>出走表がありません</h2><p>{date}・{name}{raceNo}Rは同期されていません。</p></div>:tab==="basic"?<section className={s.panel}><div className={s.panelHead}><div><p>PC-KYOTEI LIVE DATABASE</p><h2>基本出走表</h2></div><span className={s.badge}>{entries.length}艇</span></div><div className={s.entryList}>{entries.map(e=><Entry e={e} key={e.boat_no}/>)}</div></section>:tab==="previous"?<section className={`${s.panel} ${s.preparing}`}><div>📰</div><h2>一果の前日版は準備中です</h2><p>実出走表の表示は完成しています。次にIchika Brain previous_dayを接続すると、期待度・印・買い目をここへ表示できます。</p></section>:<section className={`${s.panel} ${s.preparing}`}><div>⚡</div><h2>一果の直前版は準備中です</h2><p>展示タイムと展示STは同期済みです。after_exhibition予測を接続すると、展示評価・期待度変化・最終買い目を表示できます。</p></section>}
 <nav className={s.move}>{raceNo>1?<Link className={s.moveLink} href={`/races/${String(code).padStart(2,"0")}/${raceNo-1}?date=${date}&tab=${tab}`}><span>←</span><div><small>前のレース</small><strong>{raceNo-1}R</strong></div></Link>:<div className={s.moveBlank}/>} {raceNo<12?<Link className={`${s.moveLink} ${s.moveNext}`} href={`/races/${String(code).padStart(2,"0")}/${raceNo+1}?date=${date}&tab=${tab}`}><div><small>次のレース</small><strong>{raceNo+1}R</strong></div><span>→</span></Link>:<div className={s.moveBlank}/>}</nav>
 </section></main>;
}
