'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { blankDocument } from '../../../lib/blog/document.mjs';
import { useBlogAutosave,readBlogRecovery } from './_lib/useBlogAutosave';
import s from './blogAdmin.module.css';
const TABS=['基本情報','本文ブロック','SEO','公開設定','画像'];
const ADD_TYPES=[['TEXT','文章'],['HEADING','見出し'],['POINT','POINT'],['DATA_CHECK','DATA CHECK'],['WARNING','注意事項'],['QUOTE','引用'],['IMAGE','画像'],['CTA','CTA']];
const template=type=>({id:crypto.randomUUID(),type,data:type==='HEADING'?{level:2,text:''}:type==='IMAGE'?{media_id:null,alt:'',caption:''}:type==='CTA'?{label:'レースを見る',href:'/races',text:''}:{text:''}});
async function api(path,method,body){const res=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let result;try{result=await res.json();}catch{throw new Error('サーバーの応答を確認できません。');}if(!res.ok)throw Object.assign(new Error(result.error||'処理に失敗しました。'),{status:res.status});return result;}
function stateLabel(editor){return editor?.scheduled_at?'予約':editor?.state==='published'?'公開中':editor?.state==='unpublished'?'非公開':'下書き';}
export default function BlogEditor({editor=null,catalogue,writable}){
 const [doc,setDoc]=useState(()=>editor?.document||blankDocument()),[slug,setSlug]=useState(editor?.slug||''),[tab,setTab]=useState(TABS[0]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[publishAt,setPublishAt]=useState('');const router=useRouter();
 const change=setter=>setDoc(current=>{const next=setter(current);return next;});
 async function create(){if(!writable||busy)return;setBusy(true);setMessage('');try{const result=await api('/api/admin/blog/posts','POST',{slug,document:doc});router.replace(`/admin/blog/posts/${result.id}`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <main className={s.page}><div className={s.editorHeader}><Link href="/admin/blog">← 記事一覧</Link><span className={s.badge}>{stateLabel(editor)}</span></div><header className={s.hero}><p className={s.eyebrow}>BOATSTRIKERS BLOG · EDITOR</p><h1>{editor?'記事を編集':'新しい記事'}</h1><p>{editor?'下書きの変更は自動保存されます。公開中の版は公開操作まで変わりません。':'まず記事を作成します。保存後に自動保存とプレビューを利用できます。'}</p></header>
 {!writable?<p className={s.notice}>BLOG検証環境の書き込みが無効です。入力UIを確認できますが、保存・公開はできません。</p>:null}
 {editor?<ExistingWorkspace key={editor.id} editor={editor} doc={doc} setDoc={setDoc} catalogue={catalogue} writable={writable} tab={tab} setTab={setTab} publishAt={publishAt} setPublishAt={setPublishAt} message={message} setMessage={setMessage}/>:<><nav className={s.tabs} aria-label="記事編集メニュー">{TABS.map(name=><button key={name} type="button" className={tab===name?s.active:''} onClick={()=>setTab(name)}>{name}</button>)}</nav><EditorFields {...{doc,change,slug,setSlug,tab,catalogue,newPost:true,writable}}/>{message?<p role="alert" className={s.error}>{message}</p>:null}<div className={s.actionBar}><div className={s.actionInner}><span className={s.status}>未保存変更 · 新規記事</span><button className={s.primary} disabled={!writable||busy} onClick={create}>下書きを作成</button><button className={s.button} disabled>プレビュー</button><button className={s.button} onClick={()=>setTab('公開設定')}>公開設定</button></div></div></>}
 </main>;
}
function ExistingWorkspace({editor,doc,setDoc,catalogue,writable,tab,setTab,publishAt,setPublishAt,message,setMessage}){
 const autosave=useBlogAutosave({postId:editor.id,initialVersion:editor.version,savedAt:editor.saved_at});
 const [recovery,setRecovery]=useState(null),[working,setWorking]=useState(false);
 const docRef=useRef(doc);docRef.current=doc;
 useEffect(()=>{readBlogRecovery(editor.id).then(snapshot=>{if(snapshot?.dirty)setRecovery(snapshot);});},[editor.id]);
 const change=setter=>{const next=setter(docRef.current);docRef.current=next;setDoc(next);if(writable)autosave.change(next);};
 async function save(){if(!writable)return;const result=await autosave.saveNow();if(result.status==='error')setMessage(result.error||'保存に失敗しました。');}
 async function preview(){const result=await autosave.saveNow();if(result.dirty||['error','conflict'].includes(result.status)){setMessage('未保存の変更を確認してからプレビューしてください。');return;}window.location.assign(`/admin/blog/posts/${editor.id}/preview`);}
 async function publish(action){if(!writable||working)return;setMessage('');setWorking(true);try{
   const saved=await autosave.saveNow();if(saved.dirty||saved.status!=='saved')throw new Error('保存できていない変更があります。保存状態を確認してください。');
   const endpoint=action==='publish'||action==='schedule'?'release':'state';
   const payload=endpoint==='release'?{version:saved.version,publishAt:action==='schedule'?new Date(publishAt).toISOString():null}:{version:saved.version,action};
   if(action==='schedule'&&(!publishAt||!Number.isFinite(Date.parse(publishAt))||Date.parse(publishAt)<=Date.now()))throw new Error('未来の予約日時を選択してください。');
   await api(`/api/admin/blog/posts/${editor.id}/${endpoint}`,'POST',payload);
   window.location.reload();
 }catch(e){setMessage(e.status===409?'競合が発生しました。入力内容を保持したまま、最新版を確認してください。':e.message);}finally{setWorking(false);}}
 return <><nav className={s.tabs} aria-label="記事編集メニュー">{TABS.map(name=><button key={name} type="button" className={tab===name?s.active:''} onClick={()=>setTab(name)}>{name}</button>)}</nav>
 {recovery?<div className={s.recovery}><strong>この端末に未保存の入力が残っています。</strong><p>サーバーの版 {editor.version}、端末の控え {recovery.version}。自動では上書きしません。</p>{recovery.version===editor.version&&writable?<button className={s.button} onClick={()=>{change(()=>recovery.document);setRecovery(null);}}>端末の入力を編集画面へ戻す</button>:<p>競合しているため復元できません。別の記事編集履歴を確認してください。</p>}<button className={s.button} onClick={()=>setRecovery(null)}>閉じる</button></div>:null}
 <EditorFields doc={doc} change={change} tab={tab} catalogue={catalogue} writable={writable}/>
 {tab==='公開設定'?<section className={s.panel}><h2>公開操作</h2><p className={s.info}>公開・予約は現在の編集版を確定します。自動保存は公開中の版を更新しません。予約公開の実行には別途BLOGワーカーの設定が必要です。</p><div className={s.publication}>{editor.scheduled_at?<><p>予約日時：{new Date(editor.scheduled_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</p><button className={s.button} disabled={!writable||working} onClick={()=>publish('cancel_schedule')}>予約を取り消す</button></>:<><button className={s.primary} disabled={!writable||working||autosave.status==='conflict'} onClick={()=>publish('publish')}>編集版を公開する</button><label className={s.field}>予約公開日時（端末の現地時刻）<input type="datetime-local" value={publishAt} onChange={e=>setPublishAt(e.target.value)}/></label><button className={s.button} disabled={!writable||working||!publishAt} onClick={()=>publish('schedule')}>日時を指定して予約</button></>}{editor.state==='published'?<button className={s.button} disabled={!writable||working} onClick={()=>publish('unpublish')}>公開を停止する</button>:null}</div></section>:null}
 {message?<p role="alert" className={s.error}>{message}</p>:null}
 <div className={s.actionBar}><div className={s.actionInner}><span className={s.status} data-state={autosave.status} role="status" aria-live="polite">{autosave.label}{autosave.error?`：${autosave.error}`:''}</span><button className={s.primary} disabled={!writable||working} onClick={save}>{autosave.status==='error'?'再試行':'保存'}</button><button className={s.button} onClick={preview}>プレビュー</button><button className={s.button} onClick={()=>setTab('公開設定')}>公開設定</button></div></div>
 </>;
}
function EditorFields({doc,change,tab,catalogue,slug,setSlug,newPost=false,writable=false}){
 const [media,setMedia]=useState(catalogue.media),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[alt,setAlt]=useState('');
 const edit=(key,value)=>change(d=>({...d,[key]:value}));
 async function upload(file){if(!file)return;setUploadError('');setUploading(true);try{const form=new FormData();form.set('file',file);form.set('alt',alt);const response=await fetch('/api/admin/blog/media',{method:'POST',credentials:'same-origin',body:form});const item=await response.json();if(!response.ok)throw new Error(item.error||'アップロードに失敗しました。');setMedia(current=>[item,...current]);setAlt('');}catch(e){setUploadError(e.message);}finally{setUploading(false);}}
 const editData=(id,key,value)=>change(d=>({...d,blocks:d.blocks.map(b=>b.id===id?{...b,data:{...b.data,[key]:value}}:b)}));
 const editBlock=(id,key,value)=>change(d=>({...d,blocks:d.blocks.map(b=>b.id===id?{...b,[key]:value}:b)}));
 const move=(index,direction)=>change(d=>{const blocks=[...d.blocks],to=index+direction;if(to<0||to>=blocks.length)return d;[blocks[index],blocks[to]]=[blocks[to],blocks[index]];return {...d,blocks};});
 return <>{tab==='基本情報'?<section className={s.panel}><h2>基本情報</h2>{newPost?<label className={s.field}>URL slug（英数字とハイフン）<input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="inside-course-basics" autoCapitalize="none"/></label>:null}
 <label className={s.field}>記事タイトル<input value={doc.title} onChange={e=>edit('title',e.target.value)} maxLength={200} placeholder="記事タイトル"/></label><label className={s.field}>導入・概要<textarea value={doc.excerpt} onChange={e=>edit('excerpt',e.target.value)} maxLength={2000} placeholder="この記事で扱うテーマ"/></label>
 <label className={s.field}>カテゴリー<select value={doc.category_id||''} onChange={e=>edit('category_id',e.target.value||null)}><option value="">選択してください</option>{catalogue.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><strong>著者</strong><div className={s.multi}>{catalogue.authors.map(a=><label key={a.id}><input type="checkbox" checked={doc.author_ids.includes(a.id)} onChange={e=>edit('author_ids',e.target.checked?[...doc.author_ids,a.id]:doc.author_ids.filter(x=>x!==a.id))}/>{a.name}</label>)}</div><strong>タグ</strong><div className={s.multi}>{catalogue.tags.map(t=><label key={t.id}><input type="checkbox" checked={doc.tag_ids.includes(t.id)} onChange={e=>edit('tag_ids',e.target.checked?[...doc.tag_ids,t.id]:doc.tag_ids.filter(x=>x!==t.id))}/>{t.name}</label>)}</div></section>:null}
 {tab==='本文ブロック'?<section className={s.panel}><div className={s.panelHeading}><h2>本文ブロック</h2><span>{doc.blocks.length}個</span></div><p className={s.info}>記事に必要なブロックだけ追加してください。会話シーンの本格編集は次のPHASEで対応します。既存の会話ブロックは保存時に保持します。</p><div className={s.blocks}>{doc.blocks.map((b,i)=><div className={s.block} key={b.id}><div className={s.blockHead}><strong>{b.type}</strong><div className={s.blockActions}><button aria-label="上へ" disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button aria-label="下へ" disabled={i===doc.blocks.length-1} onClick={()=>move(i,1)}>↓</button><button aria-label="削除" onClick={()=>change(d=>({...d,blocks:d.blocks.filter(x=>x.id!==b.id)}))}>×</button></div></div>{b.type==='HEADING'?<><label className={s.field}>見出しレベル<select value={b.data.level} onChange={e=>editData(b.id,'level',Number(e.target.value))}><option value="2">H2</option><option value="3">H3</option></select></label><label className={s.field}>見出し<input value={b.data.text||''} onChange={e=>editData(b.id,'text',e.target.value)}/></label></>:['TEXT','POINT','WARNING','QUOTE','DATA_CHECK'].includes(b.type)?<><label className={s.field}>文章<textarea value={b.data.text||''} onChange={e=>editData(b.id,'text',e.target.value)}/></label>{b.type!=='TEXT'?<label className={s.field}>小見出し（任意）<input value={b.data.title||''} onChange={e=>editData(b.id,'title',e.target.value)}/></label>:null}{b.type==='QUOTE'||b.type==='DATA_CHECK'?<label className={s.field}>出典URL（任意・HTTPS）<input type="url" value={b.data.source_url||''} onChange={e=>{const value=e.target.value;change(d=>({...d,blocks:d.blocks.map(x=>x.id===b.id?{...x,data:Object.fromEntries(Object.entries({...x.data,source_url:value}).filter(([k,v])=>k!=='source_url'||v))}:x)}));}}/></label>:null}</>:b.type==='IMAGE'?<><label className={s.field}>画像<select value={b.data.media_id||''} onChange={e=>editData(b.id,'media_id',e.target.value||null)}><option value="">画像を選択</option>{media.map(m=><option key={m.id} value={m.id}>{m.alt||m.id}</option>)}</select></label><label className={s.field}>代替テキスト<input value={b.data.alt||''} onChange={e=>editData(b.id,'alt',e.target.value)}/></label><label className={s.field}>キャプション<input value={b.data.caption||''} onChange={e=>editData(b.id,'caption',e.target.value)}/></label></>:b.type==='CTA'?<><label className={s.field}>ボタン文言<input value={b.data.label||''} onChange={e=>editData(b.id,'label',e.target.value)}/></label><label className={s.field}>リンク先<input value={b.data.href||''} onChange={e=>editData(b.id,'href',e.target.value)}/></label><label className={s.field}>補足文<textarea value={b.data.text||''} onChange={e=>editData(b.id,'text',e.target.value)}/></label></>:<p className={s.info}>このブロックの詳細編集はPHASE 5で対応します。内容を保持したまま保存できます。</p>}</div>)}</div><div className={s.addBlock}>{ADD_TYPES.map(([type,label])=><button key={type} onClick={()=>change(d=>({...d,blocks:[...d.blocks,template(type)]}))}>＋ {label}</button>)}</div></section>:null}
 {tab==='SEO'?<section className={s.panel}><h2>SEO</h2><label className={s.field}>検索結果のタイトル<input value={doc.seo.title||''} maxLength={200} onChange={e=>edit('seo',{...doc.seo,title:e.target.value})}/><small>未入力時は記事タイトルを使用します。</small></label><label className={s.field}>meta description<textarea value={doc.seo.description||''} maxLength={1000} onChange={e=>edit('seo',{...doc.seo,description:e.target.value})}/></label><div className={s.multi}><label><input type="checkbox" checked={doc.noindex} onChange={e=>edit('noindex',e.target.checked)}/>この記事をnoindexにする</label></div><p className={s.info}>公開URLを正規URLとして扱います。プレビュー・下書きは常にnoindexです。</p></section>:null}
 {tab==='公開設定'?<section className={s.panel}><h2>公開前の確認</h2><p className={s.info}>タイトル・カテゴリー・著者・本文を入力し、保存後に公開操作を行います。POINTやDATA CHECKなどのボックスは任意です。</p><dl><div>記事タイトル：{doc.title||'未入力'}</div><div>著者：{doc.author_ids.length}名</div><div>本文：{doc.blocks.length}ブロック</div></dl></section>:null}
 {tab==='画像'?<section className={s.panel}><h2>画像</h2><div className={s.block}><label className={s.field}>アップロードする画像の説明<input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="図の内容を説明"/></label><label className={s.field}>画像を追加（JPEG / PNG / WebP、8MB以下）<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading||!writable} onChange={e=>{upload(e.target.files?.[0]);e.target.value="";}}/></label>{uploading?<p role="status">アップロード中…</p>:null}{uploadError?<p role="alert" className={s.error}>{uploadError}</p>:null}</div><p className={s.info}>BLOG検証環境で公開利用できる画像を選択できます。IMAGEブロックの画像は「本文ブロック」で指定します。</p><label className={s.field}>アイキャッチ<select value={doc.cover.media_id||''} onChange={e=>edit('cover',{...doc.cover,media_id:e.target.value||null})}><option value="">なし</option>{media.map(m=><option key={m.id} value={m.id}>{m.alt||m.id}</option>)}</select></label><label className={s.field}>画像の説明<input value={doc.cover.alt||''} onChange={e=>edit('cover',{...doc.cover,alt:e.target.value})}/></label><div className={s.mediaChoice}>{media.map(m=><label key={m.id}><input type="radio" name="cover" checked={doc.cover.media_id===m.id} onChange={()=>edit('cover',{...doc.cover,media_id:m.id})}/>{m.public_path?<img src={m.public_path} alt={m.alt||''}/>:null}{m.alt||'登録済み画像'}</label>)}</div>{!media.length?<p className={s.empty}>BLOG用画像はまだ登録されていません。</p>:null}</section>:null}</>;
}
