import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveExhibition,selectExhibitionField,isExhibitionReady,positiveTime} from '../lib/exhibitionDisplay.js';
const first='2026-08-28T10:00:00Z', later='2026-08-28T10:01:00Z';
test('PC first is immediately usable without official response',()=>assert.equal(resolveExhibition({exhibition_time:6.8,lap_time:37,exhibition_source:'PC-KYOTEI'}).official_lap,37));
test('official first is immediately usable without PC response',()=>assert.equal(resolveExhibition({official_exhibition_time:6.8,official_lap:37}).exhibition_time,6.8));
test('invalid official value does not hide valid PC',()=>assert.equal(resolveExhibition({official_lap:0,lap_time:37}).lap_time,37));
test('newer valid PC correction replaces older official display',()=>assert.equal(resolveExhibition({official_lap:37,lap_time:36.9,official_exhibition_synced_at:first,exhibition_synced_at:later}).lap_time,36.9));
test('newer official correction replaces older PC',()=>assert.equal(resolveExhibition({official_lap:37,lap_time:36.9,official_exhibition_synced_at:later,exhibition_synced_at:first}).lap_time,37));
test('per-field provenance wins over group poll timestamp',()=>{
 const row={official_lap:37,lap_time:36.9,official_exhibition_synced_at:later,exhibition_synced_at:first,exhibition_field_meta:{official_lap:{value:37,source:'venue_official',updated_at:first},lap_time:{value:36.9,source:'PC-KYOTEI',updated_at:later}}};
 const chosen=selectExhibitionField(row,'official_lap','lap_time'); assert.equal(chosen.value,36.9);assert.equal(chosen.source,'PC-KYOTEI');
});
test('half lap never fills lap',()=>{const row=resolveExhibition({official_half_lap:18});assert.equal(row.lap_time,null);assert.equal(row.half_lap_time,18);});
test('missing field filled independently',()=>{const row=resolveExhibition({official_lap:37,straight_time:7});assert.equal(row.lap_time,37);assert.equal(row.straight_time,7);});
test('all display aliases agree',()=>{const row=resolveExhibition({lap_time:37,official_turn:11,straight_time:7});assert.equal(row.official_lap,row.lap_time);assert.equal(row.official_straight,row.straight_time);});
test('remapping after results merge is idempotent',()=>{const raw={official_lap:37,lap_time:36.9,exhibition_synced_at:later};const once=resolveExhibition(raw);assert.deepEqual(resolveExhibition({...raw,...once}),once);});
test('normal row update timestamp cannot masquerade as exhibition timestamp',()=>assert.equal(resolveExhibition({lap_time:37,updated_at:later,api_synced_at:later}).exhibition_synced_at,null));
test('mismatched metadata value is ignored',()=>assert.equal(selectExhibitionField({official_lap:37,exhibition_field_meta:{official_lap:{value:999,source:'wrong',updated_at:later}}},'official_lap','lap_time').source,'unknown'));
for(const value of [null,'',0,-1,'-',NaN,Infinity,true])test(`unusable exhibition ${String(value)}`,()=>assert.equal(positiveTime(value),null));
test('six unique valid boats required',()=>{const rows=Array.from({length:6},(_,i)=>({boat_no:i+1,exhibition_time:6.8}));assert.equal(isExhibitionReady(rows),true);assert.equal(isExhibitionReady([...rows.slice(0,5),rows[0]]),false);assert.equal(isExhibitionReady(rows.slice(0,5)),false);assert.equal(isExhibitionReady(rows.map(r=>({...r,exhibition_time:0}))),false);});
