import Image from "next/image";
import Link from "next/link";
import styles from "./how-to-use.module.css";

export const metadata = { title: "BoatStrikersの使い方", description: "一果・初音・キイナと3人のAIマスコットと一緒に、BoatStrikersの楽しみ方を紹介します。" };
const C={ichika:{n:"一果",i:"/results/icons/ichika.jpg",c:"green"},hatsune:{n:"初音",i:"/results/icons/hatsune.jpg",c:"pink"},kiina:{n:"キイナ",i:"/results/icons/kiina.jpg",c:"yellow"}};
const M={
 ichika:{n:"いちまる",imgs:["/anime/ichimaru/1E0521A6-50FF-4F73-BFEF-179EE75302BD.png","/anime/ichimaru/A670E6BB-CF59-4E69-A81C-8C309ADEEDBB.png","/anime/ichimaru/B869F3ED-D6BC-435A-8354-C157169F6B5C.png","/anime/ichimaru/E6951B58-EE42-4571-BB84-4B0977252BC9.png","/anime/ichimaru/EB9DA43E-7E37-4221-BB10-52BA666DC7B2.png"]},
 hatsune:{n:"はつころ",imgs:["/anime/hatsukoro/03DEAC32-1345-4590-BD91-3A123E264C0E.png","/anime/hatsukoro/286A2801-BD85-4A91-B753-83CBBA7CF68B.png","/anime/hatsukoro/4590CBC2-0B49-4314-B018-76FCCA64207A.png","/anime/hatsukoro/68839563-B73D-4E0A-8A0D-A6CAE2E8F599.png","/anime/hatsukoro/B4B7F524-D918-4336-8262-CBCE151357DA.png"]},
 kiina:{n:"きいもこ",imgs:["/anime/kiimoko/6712171A-5389-42A8-81C6-3D156A9B9E81.png","/anime/kiimoko/69422FEB-0DC5-4F8D-98B3-21F48D6F5B63.png","/anime/kiimoko/821F9503-E828-46A6-9574-C63B7F739718.png","/anime/kiimoko/A236743D-CDC9-4B8A-8590-3F63F6927CCC.png","/anime/kiimoko/FDA2388B-4EFF-496C-BDB7-B968A4C8C6EB.png"]}
};
function Talk({who,children,big=false}){const p=C[who];return <div className={`${styles.talk} ${styles[p.c]} ${big?styles.bigTalk:""}`}><Image src={p.i} alt={p.n} width={70} height={70}/><div><b>{p.n}</b><p>{children}</p></div></div>}
function Mate({kind,pose=0,children}){const m=M[kind];const src=m.imgs[pose%m.imgs.length];return <div className={`${styles.bot} ${styles[kind]}`}><div><b>{m.n}</b><p>{children}</p></div><figure className={styles.mateImage}><Image src={src} alt={`${m.n}のポーズ`} width={110} height={110}/><small>AI MATE</small></figure></div>}
const Head=({n,en,children})=><header className={styles.head}><span>{n}</span><div><small>{en}</small><h2>{children}</h2></div></header>;
export default function HowToUse(){return <main className={styles.page}>
<section className={styles.hero}><small>HOW TO ENJOY BOATSTRIKERS</small><h1>はじめての<br/><b>BoatStrikers</b></h1><p>AIは答えじゃない。<strong>考えるための相棒だ。</strong></p><div className={styles.faces}>{Object.values(C).map(x=><Image key={x.n} src={x.i} alt={x.n} width={92} height={92}/>)}</div><em>データを見て、3人も考える。あなたも考える。</em></section>
<section className={`${styles.story} ${styles.mangaIntro}`}><div className={styles.mangaLabel}>PROLOGUE</div><Talk who="ichika" big>はじめまして！ BoatStrikersへようこそ！ 今日は私が案内するね。私たちと一緒に、ボートレースを予想したり勉強したりできるよ。</Talk><Talk who="hatsune" big>難しいところは私も補足します♪ データを見ながら「どうなるかな？」って考えるのがBoatStrikersの楽しみ方です。</Talk><Talk who="kiina" big>でもさ、データとかAIって難しそうじゃない？ 私と同じ目線で、分からないことはどんどん聞いていこっ！</Talk><div className={styles.reveal}><span>まず紹介したいのは…</span><strong>3人の小さな相棒！</strong></div></section>
<section className={`${styles.chapter} ${styles.partnerChapter}`}><Head n="01" en="BOATSTRIKERS AI MATES">3人の小さな相棒</Head><Talk who="ichika">私たちには、それぞれの予想の考え方をもとにデータを調べてくれる小さな相棒がいるの。</Talk><div className={styles.botSplash}><Mate kind="ichika" pose={0}>イン逃げ研究担当！ 一果の考え方をもとに、過去データからイン戦を研究するよ！</Mate><Mate kind="hatsune" pose={1}>女子戦研究担当♪ 初音の視点をもとに、女子戦の傾向や選手データを調べます！</Mate><Mate kind="kiina" pose={2}>穴・5アタマ研究担当！ 穴の気配を見つけたらすぐ反応！ 条件をデータから探すよ！</Mate></div><Talk who="kiina">きいもこ、やっぱり穴の気配には敏感だね（笑） でも、この子たちがサイトのAI参考予想を担当するってこと？</Talk><Talk who="hatsune">そう♪ 3人本人の最終予想じゃなくて、まずはデータから「こういう傾向があるよ」と教えてくれる分析担当なんです。</Talk><div className={styles.explainBox}><b>AI MATES ＝ データを調べる小さな相棒</b><p>いちまる・はつころ・きいもこは、一果・初音・キイナそれぞれの予想思想をもとに過去データを分析するAIマスコット。ここから3人もユーザーも、自分なりに考えていきます。</p></div></section>
<section className={styles.chapter}><Head n="02" en="AI DATA FORECAST">まずAIの参考予想を見る</Head><Mate kind="ichika" pose={1}>今日のイン逃げ期待度は <strong>76%</strong>！ 過去の類似条件ではイン優勢だよ。</Mate><Talk who="kiina" big>76%！？ じゃあ1号艇を買えばいいってこと？</Talk><Talk who="ichika" big>ちょっと待った！ そこが大事。76%だから「絶対に逃げる」とか「そのまま買えばいい」という意味じゃないよ。</Talk><Talk who="hatsune">AIが出した数字は、過去データから考えるための材料のひとつ。展示や選手、オッズも合わせて見ていこう♪</Talk><div className={styles.message}><s>AI予想 ＝ 答え</s><b>AI予想 ＝ 考える材料</b></div></section>
<section className={styles.chapter}><Head n="03" en="THINK YOURSELF">AIを見て、自分でも考える</Head><Talk who="kiina">なるほど！ 「76%だから買う！」じゃなくて、そこから自分でも考えるんだね。</Talk><Talk who="ichika">その通り！ AIの数字を入口にして、レースをいろんな視点で見てみよう。</Talk><Talk who="hatsune">展示、選手の調子、進入、気象、オッズ……。ひとつずつ確認すると、数字の見え方も変わってきます♪</Talk><div className={styles.chips}>{["AI分析","展示","選手","気象・進入","オッズ","あなたの考え"].map(x=><span key={x}>{x}</span>)}</div></section>
<section className={styles.chapter}><Head n="04" en="WE THINK TOO">実は3人もAI MATESを見ています</Head><Talk who="kiina" big>でもさ、一果や初音は自分で予想できるんだから、AIなんて見なくてもいいんじゃない？</Talk><div className={styles.trioAnswer}>一果・初音「見るよ！」</div><Talk who="kiina">え、見るんだ（笑）</Talk><Mate kind="ichika" pose={3}>一果さん、今日の分析できました！</Mate><Talk who="ichika">もちろん見るよ。いちまるの分析を参考にして、そこから展示や当日の情報、オッズも確認して自分で考えるの。</Talk><Talk who="hatsune">私たちもユーザーのみんなと同じです。AIを参考にはするけど、AIだけで決めるわけじゃないんです♪</Talk><Talk who="kiina">なるほど。AI MATESが調べて、一果たちも考える。私たちも考える。そういう使い方なんだね！</Talk><div className={styles.flow}><b>DATA</b><i>↓</i><strong>AI MATESが分析</strong><div><span>↙ 3人が考える</span><span>あなたが考える ↘</span></div></div></section>
<section className={styles.chapter}><Head n="05" en="TWO EDITIONS">前日版と直前版</Head><Talk who="kiina">じゃあ、前日版と直前版って何が違うの？</Talk><Talk who="ichika">前日版はAI MATESと予習するイメージ。前日時点で使えるデータから参考予想を出すよ。</Talk><Talk who="hatsune">直前版では、AI分析に展示・当日情報・オッズなどを加えて、私たち3人が考察します♪</Talk><div className={styles.cards}><article><b>🌙 前日版</b><h3>AI MATESと予習する</h3><p>前日時点で利用できるデータから、AI MATESが参考予想。</p></article><article><b>☀️ 直前版</b><h3>3人と考える</h3><p>AI分析＋展示・当日情報・オッズなどを見て、3人が考察。</p></article></div></section>
<section className={styles.chapter}><Head n="06" en="BOAT NIGHT NIPPON">ラジオでは一緒に考える</Head><Talk who="ichika">ラジオでは、AI MATESの分析を見ながら私たちが実際に考えていくよ。いちまる、今日のイン戦どう？</Talk><Mate kind="ichika" pose={4}>イン逃げ期待度78%です！</Mate><Talk who="kiina">78%かぁ。でもオッズが低かったらどうする？</Talk><Talk who="hatsune">そこをみんなで話すのがラジオの面白いところ♪ 展示や相手候補も一緒に見ていこう。</Talk><Link className={styles.link} href="/radio">ボート・ナイト・ニッポンを見る →</Link></section>
<section className={styles.chapter}><Head n="07" en="REVIEW & LEARN">当たった・外れたで終わらない</Head><Talk who="kiina">当たったら勝ち！ 外れたら負け！ ……で終わりじゃないの？</Talk><Talk who="ichika">そこも大事なポイント。予想がどうだったかだけじゃなく、どんな買い方をしたかまで振り返ろう。</Talk><Talk who="hatsune">的中率だけじゃなく、回収率や「なぜそう考えたか」も見直すと、次の予想につながります♪</Talk><div className={styles.cycle}>予想 → 考える → 観戦 → 結果 → 振り返る</div></section>
<section className={styles.choose}><small>CHOOSE YOUR STYLE</small><h2>あなたはどう楽しむ？</h2><div><Link href="/today"><b>🌱 まずは楽しむ</b><span>今日のBoatStrikersを見る</span></Link><Link href="/data-lab"><b>🔬 もっと研究する</b><span>DATA LABで学ぶ</span></Link><Link href="/library"><b>📚 3人の考えを知る</b><span>研究記事・読み物を見る</span></Link></div></section>
<section className={styles.final}><div className={styles.faces}>{Object.values(C).map(x=><Image key={x.n} src={x.i} alt={x.n} width={82} height={82}/>)}</div><h2>AIは答えじゃない。<br/>考えるための相棒だ。</h2><p>AI MATESがデータを調べる。3人も考える。あなたも考える。</p><Link href="/today">今日のBoatStrikersを見る</Link><small>舟券の購入は20歳になってから。予想・データは的中や利益を保証するものではありません。</small></section>
</main>}