import Image from "next/image";
import Link from "next/link";
import styles from "./how-to-use.module.css";

export const metadata = { title: "BoatStrikersの使い方", description: "一果・初音・キイナと会話しながらBoatStrikersの楽しみ方を紹介します。" };
const C={ichika:{n:"一果",i:"/results/icons/ichika.jpg",c:"green"},hatsune:{n:"初音",i:"/results/icons/hatsune.jpg",c:"pink"},kiina:{n:"キイナ",i:"/results/icons/kiina.jpg",c:"yellow"}};
function Talk({who,children,big=false}){const p=C[who];return <div className={`${styles.talk} ${styles[p.c]} ${big?styles.bigTalk:""}`}><Image src={p.i} alt={p.n} width={70} height={70}/><div><b>{p.n}</b><p>{children}</p></div></div>}
function Bot({kind,name,children}){return <div className={`${styles.bot} ${styles[kind]}`}><div><b>{name}</b><p>{children}</p></div><figure><span>● ●</span><strong>{kind==="ichika"?"1":kind==="hatsune"?"V":"5"}</strong></figure></div>}
const Head=({n,en,children})=><header className={styles.head}><span>{n}</span><div><small>{en}</small><h2>{children}</h2></div></header>;
export default function HowToUse(){return <main className={styles.page}>
<section className={styles.hero}><small>HOW TO ENJOY BOATSTRIKERS</small><h1>はじめての<br/><b>BoatStrikers</b></h1><p>AIは答えじゃない。<strong>考えるための相棒だ。</strong></p><div className={styles.faces}>{Object.values(C).map(x=><Image key={x.n} src={x.i} alt={x.n} width={92} height={92}/>)}</div><em>データを見て、3人も考える。あなたも考える。</em></section>
<section className={`${styles.story} ${styles.mangaIntro}`}><div className={styles.mangaLabel}>PROLOGUE</div><Talk who="ichika" big>はじめまして！ BoatStrikersへようこそ！ 私たちと一緒にボートレースを予想したり、勉強したりできるよ。</Talk><Talk who="hatsune" big>データを見て、みんなで「どうなるかな？」って考えるのがBoatStrikersの楽しみ方です♪</Talk><Talk who="kiina" big>でも私たちだけじゃないんだよね！ 私たちには、データ分析がすご〜く得意な小さな相棒がいるんだよ！</Talk><div className={styles.reveal}><span>その相棒とは…</span><strong>ピコーン！</strong></div></section>
<section className={`${styles.chapter} ${styles.partnerChapter}`}><Head n="01" en="OUR PARTNERS">3人の小さな相棒</Head><div className={styles.botSplash}><Bot kind="ichika" name="いちまる（仮）">イン逃げ解析担当！ 一果の考え方をもとに、過去データからイン戦を研究するよ！</Bot><Bot kind="hatsune" name="はつまる（仮）">女子戦解析担当♪ 初音の視点をもとに、女子戦の傾向や選手データを調べます！</Bot><Bot kind="kiina" name="きいまる（仮）">穴・5アタマ解析担当！ 5号艇反応ありっ！ 穴になりそうな条件を探すよ！</Bot></div><Talk who="kiina">きいまる、まだレースも見てないのに5号艇って言ってない？（笑）</Talk><div className={styles.explainBox}><b>この3体は何をしているの？</b><p>一果・初音・キイナそれぞれの予想思想をもとに、過去データを分析するAIアシスタントです。3人本人の予想ではなく、考えるための「データ担当」です。</p></div></section>
<section className={styles.chapter}><Head n="02" en="AI DATA FORECAST">まずAIの参考予想を見る</Head><Bot kind="ichika" name="いちまる（仮）">今日のイン逃げ期待度は <strong>76%</strong>！ 過去の類似条件ではイン優勢だよ。</Bot><div className={styles.userQuestion}><span>USER</span><p>76%！ じゃあ1号艇を買えばいいの？</p></div><Talk who="ichika" big>ちょっと待った！ 76%だから「絶対に逃げる」という意味じゃないよ。</Talk><div className={styles.message}><s>AI予想 ＝ 答え</s><b>AI予想 ＝ 考える材料</b></div></section>
<section className={styles.chapter}><Head n="03" en="THINK YOURSELF">AIを見て、自分でも考える</Head><Talk who="hatsune">AIの数字を見たら、展示や選手の調子、進入、気象も見てみよう！</Talk><Talk who="kiina">そしてオッズも大事！「当たりそう」と「買いたい」は同じじゃないからね。</Talk><div className={styles.chips}>{["AI分析","展示","選手","気象・進入","オッズ","あなたの考え"].map(x=><span key={x}>{x}</span>)}</div></section>
<section className={styles.chapter}><Head n="04" en="WE THINK TOO">実は3人もAIを見ています</Head><div className={styles.userQuestion}><span>USER</span><p>でも一果たちはAIを見ないで、自分だけで予想するんでしょ？</p></div><div className={styles.trioAnswer}>3人「見るよ？」</div><Bot kind="ichika" name="いちまる（仮）">一果さん、今日の分析できました！</Bot><Talk who="ichika">ありがとう！ 展示や当日の情報も見て、ここから自分で考えてみるね。</Talk><Talk who="hatsune">私たちもみんなと同じ。AIを参考にするけど、AIだけで決めるわけじゃないんです。</Talk><Talk who="kiina">AIと意見が違う日があってもOK。それも予想の面白いところ！</Talk><div className={styles.flow}><b>DATA</b><i>↓</i><strong>AIアシスタントが分析</strong><div><span>↙ 3人が考える</span><span>あなたが考える ↘</span></div></div></section>
<section className={styles.chapter}><Head n="05" en="TWO EDITIONS">前日版と直前版</Head><div className={styles.cards}><article><b>🌙 前日版</b><h3>AIと予習する</h3><p>前日時点で利用できるデータから、AIアシスタントが参考予想。</p></article><article><b>☀️ 直前版</b><h3>3人と考える</h3><p>AI分析＋展示・当日情報・オッズなどを見て、3人が考察。</p></article></div></section>
<section className={styles.chapter}><Head n="06" en="BOAT NIGHT NIPPON">ラジオでは一緒に考える</Head><Talk who="ichika">いちまる、今日のイン戦どう？</Talk><Bot kind="ichika" name="いちまる（仮）">イン逃げ期待度78%です！</Bot><Talk who="hatsune">でも2号艇の展示も気になるなぁ。</Talk><Talk who="kiina">私はオッズを見てから決めたい！</Talk><Link className={styles.link} href="/radio">ボート・ナイト・ニッポンを見る →</Link></section>
<section className={styles.chapter}><Head n="07" en="REVIEW & LEARN">当たった・外れたで終わらない</Head><Talk who="ichika">予想はどうだった？</Talk><Talk who="hatsune">どこを見ればよかった？</Talk><Talk who="kiina">的中率だけじゃなく、回収率や買い方も振り返ろう！</Talk><div className={styles.cycle}>予想 → 考える → 観戦 → 結果 → 振り返る</div></section>
<section className={styles.choose}><small>CHOOSE YOUR STYLE</small><h2>あなたはどう楽しむ？</h2><div><Link href="/today"><b>🌱 まずは楽しむ</b><span>今日のBoatStrikersを見る</span></Link><Link href="/data-lab"><b>🔬 もっと研究する</b><span>DATA LABで学ぶ</span></Link><Link href="/library"><b>📚 3人の考えを知る</b><span>研究記事・読み物を見る</span></Link></div></section>
<section className={styles.final}><div className={styles.faces}>{Object.values(C).map(x=><Image key={x.n} src={x.i} alt={x.n} width={82} height={82}/>)}</div><h2>AIは答えじゃない。<br/>考えるための相棒だ。</h2><p>AIがデータを調べる。3人も考える。あなたも考える。</p><Link href="/today">今日のBoatStrikersを見る</Link><small>舟券の購入は20歳になってから。予想・データは的中や利益を保証するものではありません。</small></section>
</main>}