import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
export const dynamic="force-dynamic";export const runtime="nodejs";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Supabase環境変数が未設定です");return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}});}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function key(r){return `${r.race_date}-${Number(r.course_code)}-${Number(r.race_no)}`;}
function stats(rows){const f=rows.filter(r=>Array.isArray(r.result_top3)&&r.result_top3.length===3);const out3=f.filter(r=>!r.result_top3.includes(1)).length;const hit=(nums)=>f.filter(r=>nums.every(n=>r.result_top3.includes(n))&&r.result_top3.every(n=>nums.includes(n))).length;return {matched:rows.length,finished:f.length,out3,out3Rate:f.length?out3/f.length:null,hit234:hit([2,3,4]),hit235:hit([2,3,5]),hit345:hit([3,4,5])};}
async function enrich(s,rows){if(!rows.length)return rows;const ds=rows.map(r=>r.race_date).sort();const {data,error}=await s.from("bs_race_entries").select("race_date,course_code,race_no,boat_no,arrival_order").gte("race_date",ds[0]).lte("race_date",ds[ds.length-1]);if(error)throw error;const map=new Map();for(const e of data||[]){const k=key(e);if(!map.has(k))map.set(k,[]);map.get(k).push(e);}return rows.map(r=>{const es=map.get(key(r))||[];const top3=es.filter(e=>[1,2,3].includes(Number(e.arrival_order))).sort((a,b)=>Number(a.arrival_order)-Number(b.arrival_order)).map(e=>Number(e.boat_no));return {...r,result_top3:top3,result_combo:top3.length===3?top3.join("-"):null};});}
export async function GET(req){try{const s=db(),q=new URL(req.url).searchParams,date=q.get("date")||today(),mode=q.get("mode")||"day";const fields="id,race_date,course_code,course_name,race_no,closing_time,box_234_rating,box_235_rating,box_345_rating,boat1_win_rate,boat2_win_rate,boat3_win_rate,boat4_win_rate,boat5_win_rate,boat6_win_rate,boat1_exhibition_rank,boat2_exhibition_rank,boat3_exhibition_rank,boat4_exhibition_rank,boat5_exhibition_rank,boat6_exhibition_rank,danger_level,detected_at,notified,notified_at";let x=s.from("bs_hatsune_womens_inner_break_alerts").select(fields).order("race_date",{ascending:false}).order("closing_time",{ascending:false}).limit(5000);if(mode!=="all")x=x.eq("race_date",date);const {data,error}=await x;if(error)throw error;const rows=await enrich(s,data||[]);return NextResponse.json({ok:true,date,mode,alerts:rows,stats:stats(rows),allStats:stats(rows),daily:[]});}catch(e){return NextResponse.json({ok:false,error:e?.message||"取得に失敗しました"},{status:500});}}
export async function POST(){try{const s=db();const {data,error}=await s.rpc("evaluate_hatsune_womens_inner_break_alerts");if(error)throw error;return NextResponse.json({ok:true,inserted:Number(data||0)});}catch(e){return NextResponse.json({ok:false,error:e?.message||"判定に失敗しました"},{status:500});}}
