"use client";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import styles from "./page.module.css";
const GRADES=["ALL","SG","PG1","G1","G2","G3"],yen=v=>Number(v||0).toLocaleString("ja-JP"),pct=v=>v==null?"集計待ち":`${Number(v).toFixed(1)}%`;
function yesterday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(Date.now()-86400000));}
function build(e,date){if(!e)return"";const rows=[e.result_count>0&&`結果確定：${e.result_count}R`,e.boat1_win_rate!=null&&`1号艇1着率：${pct(e.boat1_win_rate)}`,e.manshu_count!=null&&`万舟：${e.manshu_count}本`,e.avg_payout!=null&&`平均3連単配当：${yen(Math.round(e.avg_payout))}円`].filter(Boolean);return`BoatStrikers DATA LABのX投稿専用【グレードレース・横長コンパクト画像】を作成してください。\n\n【共通ルール】\n・横長16:9、1200×675px\n・濃紺・ダークブルー・白・ゴールドのDATA LAB世界観\n・この開催だけの確定データを使用し、他場・一般戦の数字を絶対に混ぜない\n・未確定、空欄、該当なしの項目はカードごと削除する\n・数値、出目、配当を推測しない\n・主要数字は3〜5項目に絞る\n・下部に BoatStrikers / boat-strike.online\n\n【対象開催｜${date}】\n${e.grade} ${e.course_name}\n${e.title}\n${e.day_no?`${e.day_no}日目`:""}\n${rows.join("\n")||"結果集計待ち"}\n\n上部に「${e.grade} ${e.title} DATA LAB」。開催名とグレードを大きく、その下にこの開催だけの主要数字を配置してください。`;}
export default function GradeRaceImageBuilder(){const sp=useSearchParams(),q=sp.get("date")||"",date=/^\d{4}-\d{2}-\d{2}$/.test(q)?q:yesterday();const[events,setEvents]=useState([]),[grade,setGrade]=useState("ALL"),[selected,setSelected]=useState(""),[copied,setCopied]=useState(false),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;setLoading(true);fetch(`/api/admin/grade-races?date=${encodeURIComponent(date)}&mode=data`).then(r=>r.json()).then(j=>{if(live){setEvents(Array.isArray(j.events)?j.events:[]);setLoading(false)}}).catch(()=>{if(live){setEvents([]);setLoading(false)}});return()=>{live=false}},[date]);const filtered=useMemo(()=>grade==="ALL"?events:events.filter(e=>e.grade===grade),[events,grade]);useEffect(()=>{if(!filtered.some(e=>String(e.course_code)===selected))setSelected(filtered[0]?String(filtered[0].course_code):"")},[filtered,selected]);const event=filtered.find(e=>String(e.course_code)===selected)||null,prompt=useMemo(()=>build(event,date),[event,date]);async function copy(){try{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}}
return <section className={`${styles.promptBuilder} ${styles.gradeBuilder}`}>
<div className={styles.gradeBuilderHero}><span className={styles.promptEyebrow}>GRADE RACE IMAGE BUILDER</span><h3>グレード戦画像を作る</h3><p>SG・PG1・G1・G2・G3から開催を選び、その開催だけの確定データで16:9画像を作ります。</p></div>
{loading?<p className={styles.gradeEmpty}>グレード戦を読み込み中...</p>:<div className={styles.gradeBuilderBody}>
<div className={styles.gradeSelectCard}><div className={styles.gradeStepTitle}><b>1</b><span>グレード・開催を選択</span></div><div className={styles.gradeSelectorLayout}><div><label className={styles.gradeLabel}>グレードで絞り込み</label><div className={styles.gradeButtons}>{GRADES.map(g=><button key={g} type="button" className={`${styles.presetButton} ${grade===g?styles.active:""}`} onClick={()=>setGrade(g)}>{g==="ALL"?"すべて":g}</button>)}</div></div><div><label className={styles.gradeLabel}>対象開催</label>{filtered.length===0?<div className={styles.gradeEmpty}>この日付・グレードの開催はありません。</div>:<select className={styles.gradeEventSelect} value={selected} onChange={e=>setSelected(e.target.value)}>{filtered.map(e=><option key={`${e.course_code}-${e.title}`} value={e.course_code}>{e.grade} {e.course_name}｜{e.title}{e.day_no?`｜${e.day_no}日目`:""}</option>)}</select>}</div></div></div>
{event&&<><div className={styles.gradeSummaryGrid}><div className={styles.gradeSummaryCard}><div className={styles.gradeStepTitle}><b>2</b><span>開催サマリー</span></div><h4>{event.course_name} <em>{event.grade}</em> {event.title}</h4><p className={styles.gradeDate}>{date}{event.day_no?` ｜ ${event.day_no}日目`:""}</p><div className={styles.gradeStats}><div><span>結果確定</span><strong>{event.result_count}R</strong></div><div><span>1号艇1着率</span><strong>{pct(event.boat1_win_rate)}</strong></div><div><span>万舟</span><strong>{event.manshu_count}本</strong></div><div><span>平均3連単配当</span><strong>{event.avg_payout?`${yen(Math.round(event.avg_payout))}円`:"集計待ち"}</strong></div></div></div><div className={styles.gradeActionCard}><div className={styles.gradeStepTitle}><b>3</b><span>画像用プロンプト</span></div><div className={styles.gradeMockPreview}><span>{event.course_name}</span><strong><i>{event.grade}</i>{event.title}</strong><small>BoatStrikers DATA LAB</small></div><button className={styles.promptCopyButton} type="button" onClick={copy}>{copied?"コピーしました ✓":"この開催だけの画像プロンプトをコピー"}</button></div></div><div className={styles.gradePromptCard}><div className={styles.gradeStepTitle}><b>4</b><span>生成されるプロンプト</span></div><textarea className={styles.promptTextarea} readOnly value={prompt}/></div></>}
</div>}</section>}
