"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./page.module.css";

const PRESETS=[{key:"three",label:"3人入り固定テンプレ",tone:"一果・初音・キイナを上部に配置するBoatStrikers標準版。"},{key:"simple",label:"データ優先版",tone:"キャラクターは入れず、濃紺・白・ゴールドのデータ番組風。"},{key:"luxury",label:"高級感版",tone:"3人は小さめ。プレミアムなスポーツデータ誌の雰囲気。"},{key:"anime",label:"キャラ強め版",tone:"3人を少し大きめにし、親しみやすさを強める。"}];
const OUTPUT_MODES=[{key:"cover",label:"共通表紙 1枚",detail:null},{key:"common",label:"共通 2枚",detail:"common"},{key:"ichika",label:"一果 2枚",detail:"ichika"},{key:"hatsune",label:"初音 2枚",detail:"hatsune"},{key:"kiina",label:"キイナ 2枚",detail:"kiina"}];
function statsMap(p){const m={};(Array.isArray(p?.stats)?p.stats:[]).forEach(s=>m[String(s.label||"")]=String(s.value||""));return m}
function topText(p){const x=p?.max_payout;return x?`${x.venue||""}${x.race_no||""}R ${x.trifecta||""} / ${Number(x.payout||0).toLocaleString("ja-JP")}円`:"該当なし"}
function rankingLines(p){const a=Array.isArray(p?.venue_manshu_ranking)?p.venue_manshu_ranking:[];return a.length?a.slice(0,5).map((r,i)=>`${i+1}. ${r.venue||""} ${r.count||0}本`).join("\n"):"該当なし"}
function detail(p,k){const d=p?.character_details||{};return d?.[k]&&typeof d[k]==="object"?d[k]:{}}
function n(v,s=""){return v===null||v===undefined||v===""?"該当なし":`${v}${s}`}
function venues(a){if(!Array.isArray(a)||!a.length)return"該当なし";return a.slice(0,3).map((r,i)=>`${i+1}. ${r?.venue||""}${Number.isFinite(Number(r?.rate))?` ${Number(r.rate).toFixed(1)}%`:""}${r?.count!==undefined?`（逃げ${r.count}R / ${r.race_count||0}R）`:""}`).join("\n")}
function races(a,l=3){if(!Array.isArray(a)||!a.length)return"該当なし";return a.slice(0,l).map((r,i)=>`${i+1}. ${r?.venue||""}${r?.race_no?`${r.race_no}R`:""}${r?.trifecta?` ${r.trifecta}`:""}${Number(r?.payout||0)>0?` / ${Number(r.payout).toLocaleString("ja-JP")}円`:""}`).join("\n")}
function roughVenues(a){if(!Array.isArray(a)||!a.length)return"該当なし";return a.slice(0,3).map((r,i)=>`${i+1}. ${r?.venue||""} 万舟${r?.count||0}本 / 最高${Number(r?.max_payout||0).toLocaleString("ja-JP")}円`).join("\n")}
const RULE=`【重要ルール】\n・確定データだけを使用し、数値・場名・出目・配当を推測しない\n・空欄のカードや順位枠を作らない\n・値が「該当なし」の項目は、見出し・カード・ランキング枠ごと画像から削除する\n・削除して空いたスペースは、残った主要数値・メモ・キャラクターを拡大して自然に詰める\n・「[object Object]」を絶対に表示しない\n・「事故・異常者」「異常者」「事故・異常着」は使用せず「事故レース」と表記する`;
function buildCoverPrompt(p,preset){const s=statsMap(p);return `BoatStrikers DATA LABの9:16縦長SNS画像【1枚目・共通表紙】を作成してください。\n1080×1920、濃紺・ダークブルー・白・ゴールド。\n${RULE}\n\n【選択デザイン】\n${preset.label}\n${preset.tone}\n\n【確定データ】\n日付：${p?.date||""}\nタイトル：${p?.title||"昨日のボートレースを数字で見る"}\n開催：${s["開催"]||"該当なし"}\n万舟：${s["万舟"]||"0本"}\n万舟率：${s["万舟率"]||"0%"}\n1号艇1着：${s["1号艇1着"]||"0R"}\n5号艇1着：${s["5号艇1着"]||"0R"}\n逃げ：${s["逃げ"]||"0R"}\n最高配当：${topText(p)}\n万舟が多かった場TOP5：\n${rankingLines(p)}\n事故レース：${p?.incident_races||0}R\n優勝戦・DR：${p?.featured_races||0}R\n\n上部に一果・初音・キイナ、中央〜下部にデータカード。空欄は作らず実データだけで完成させる。`}
function buildDetailPrompt(p,mode){const s=statsMap(p),date=p?.date||"",esc=s["逃げ"]||"0R",rm=esc.match(/\(([^)]+)\)/),rate=rm?rm[1]:"該当なし",i=detail(p,"ichika"),h=detail(p,"hatsune"),k=detail(p,"kiina");const base=`BoatStrikers DATA LABの9:16縦長SNS画像【2枚目・キャラ別詳細】を作成してください。\n1080×1920、1枚目と同じ濃紺・ダークブルー・白・ゴールド。\n${RULE}\n日付：${date}\n\n`;
if(mode==="ichika")return `${base}【一果｜イン逃げ特化】\nテーマ「イン逃げで昨日を読む」。一果を上部、緑アクセント。\n\n【確定データ】\n1号艇1着：${s["1号艇1着"]||"該当なし"}\n逃げ：${esc}\n逃げ率：${rate}\nイン逃げ成功数：${n(i.escape_success_count,"R")}\nイン崩れ数：${n(i.escape_failure_count,"R")}\nイン逃げが強かった場 TOP3：\n${venues(i.strong_venues)}\nイン崩れ注目レース TOP3：\n${races(i.upset_races)}\n一果メモ：${i.comment||"該当なし"}\n\nTOP3が該当なしならランキング欄そのものを作らない。主要4数値と一果メモを大きくして空きスペースを埋める。`;
if(mode==="hatsune")return `${base}【初音｜女子戦特化】\n初音を上部、紫・ピンクアクセント。\n\n【確定データ】\n女子戦数：${n(h.women_race_count,"R")}\n女子戦1号艇1着：${n(h.women_boat1_wins,"R")}\n女子戦逃げ数：${n(h.women_escape_count,"R")}\n女子戦逃げ率：${n(h.women_escape_rate,"%")}\n女子戦万舟数：${n(h.women_manshu_count,"本")}\n女子戦最高配当：${h.women_max_payout?races([h.women_max_payout],1).replace(/^1\. /,""):"該当なし"}\n荒れた女子戦 TOP3：\n${races(h.rough_races)}\n注目女子戦 TOP3：\n${races(h.featured_races)}\n初音メモ：${h.comment||"該当なし"}\n\n該当なしの項目は枠ごと削除し、女子戦の実データだけで再構成する。`;
if(mode==="kiina")return `${base}【キイナ｜穴・高配当特化】\nキイナを上部、黄色・ゴールドアクセント。\n\n【確定データ】\n万舟本数：${s["万舟"]||"0本"}\n万舟率：${s["万舟率"]||"0%"}\n最高配当：${topText(p)}\n5号艇1着：${s["5号艇1着"]||"0R"}\n4〜6号艇頭の高配当件数：${n(k.outer_head_big_payout_count,"R")}\n荒れた場 TOP3：\n${roughVenues(k.rough_venues)}\n高配当レース TOP5：\n${races(k.payout_top5,5)}\nキイナメモ：${k.comment||"該当なし"}\n\n該当なしの項目は枠ごと削除し、穴・高配当の実データだけで再構成する。`;
return `${base}【共通詳細】\n開催：${s["開催"]||"該当なし"}\n万舟：${s["万舟"]||"0本"}\n万舟率：${s["万舟率"]||"0%"}\n1号艇1着：${s["1号艇1着"]||"0R"}\n5号艇1着：${s["5号艇1着"]||"0R"}\n逃げ：${esc}\n最高配当：${topText(p)}\n万舟TOP5：\n${rankingLines(p)}\n事故レース：${p?.incident_races||0}R\n優勝戦・DR：${p?.featured_races||0}R\n\n該当なしの項目は枠ごと削除する。`}
export default function PromptBuilder({payload}){const[presetKey,setPresetKey]=useState("three"),[modeKey,setModeKey]=useState("common"),[copiedKey,setCopiedKey]=useState("");useEffect(()=>{try{const p=localStorage.getItem("bs_data_lab_prompt_preset"),m=localStorage.getItem("bs_data_lab_output_mode");if(p&&PRESETS.some(x=>x.key===p))setPresetKey(p);if(m&&OUTPUT_MODES.some(x=>x.key===m))setModeKey(m)}catch{}},[]);const preset=PRESETS.find(p=>p.key===presetKey)||PRESETS[0],mode=OUTPUT_MODES.find(m=>m.key===modeKey)||OUTPUT_MODES[1],coverPrompt=useMemo(()=>buildCoverPrompt(payload||{},preset),[payload,preset]),detailPrompt=useMemo(()=>mode.detail?buildDetailPrompt(payload||{},mode.detail):"",[payload,mode]);function cp(v){setPresetKey(v);try{localStorage.setItem("bs_data_lab_prompt_preset",v)}catch{}}function cm(v){setModeKey(v);try{localStorage.setItem("bs_data_lab_output_mode",v)}catch{}}async function copy(key,text){try{await navigator.clipboard.writeText(text);setCopiedKey(key);setTimeout(()=>setCopiedKey(""),1600)}catch{}}return <section className={styles.promptBuilder}><div className={styles.promptHeader}><div><span className={styles.promptEyebrow}>DATA LAB SERIES BUILDER</span><h3>DATA LAB画像生成プロンプト</h3></div><div className={styles.promptSelectors}><select value={modeKey} onChange={e=>cm(e.target.value)}>{OUTPUT_MODES.map(m=><option value={m.key} key={m.key}>{m.label}</option>)}</select><select value={presetKey} onChange={e=>cp(e.target.value)}>{PRESETS.map(p=><option value={p.key} key={p.key}>{p.label}</option>)}</select></div></div><p className={styles.promptDescription}>出力形式：{mode.label}。空データの枠は作らず、実データがある項目だけで画像を構成します。</p><div className={styles.promptPageLabel}>1枚目｜共通表紙</div><textarea className={styles.promptTextarea} readOnly value={coverPrompt}/><button className={styles.promptCopyButton} type="button" onClick={()=>copy("cover",coverPrompt)}>{copiedKey==="cover"?"コピーしました ✓":"1枚目のプロンプトをコピー"}</button>{detailPrompt&&<><div className={styles.promptPageLabel}>2枚目｜{mode.label.replace(" 2枚","")}詳細</div><textarea className={styles.promptTextarea} readOnly value={detailPrompt}/><button className={styles.promptCopyButton} type="button" onClick={()=>copy("detail",detailPrompt)}>{copiedKey==="detail"?"コピーしました ✓":"2枚目のプロンプトをコピー"}</button></>}<p className={styles.note}>該当データがない項目は空欄表示せず省略します。ランキング配列は画像生成向けの日本語へ整形します。</p></section>}
