const chapter1 = [
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "こんにちは😊\nBOAT STRIKERSへようこそ♪",
    autoNext: true,
    delay: 600,
  },
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "今日は競艇の基本を一緒に覚えよう✨",
    autoNext: true,
    delay: 900,
  },
  {
    type: "talk",
    character: "ichika",
    face: "thinking",
    text: "まずは超基本！\n競艇は何艇で走るか知ってる？",
    autoNext: true,
    delay: 900,
  },
  {
    type: "quiz",
    character: "ichika",
    face: "thinking",
    question: "競艇は基本的に何艇で走る？",
    choices: ["4艇", "6艇", "8艇"],
    answer: 1,
    correctText: "正解！！\n競艇は6艇で走るよ🚤✨",
    wrongText: "惜しい！\n競艇は6艇で走るんだよ♪",
  },
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "いい感じ！\nじゃあ次は、どこで走るか確認しよう♪",
    autoNext: true,
    delay: 900,
  },
  {
    type: "quiz",
    character: "ichika",
    face: "thinking",
    question: "競艇はどこで行われる？",
    choices: ["水面", "芝生", "道路"],
    answer: 0,
    correctText: "ピンポーン！\n水面を走るレースだよ😊",
    wrongText: "惜しい！\n競艇は水面で行われるよ♪",
  },
    {
    type: "quiz",
    character: "ichika",
    face: "thinking",
    question: "競艇は何周する？",
    choices: ["2周", "3周", "4周"],
    answer: 1,
    correctText: "ピンポーン！\n水面を走るレースだよ😊",
    wrongText: "惜しい！\n競艇は水面で行われるよ♪",
  },
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "すごい！\nこれで競艇の基本はバッチリ✨",
    autoNext: true,
    delay: 900,
  },
  {
    type: "clear",
    character: "ichika",
    face: "happy",
    text: "MISSION CLEAR！\n競艇入門認定、GETだよ🏅",
  },
];

export default chapter1;
