const chapter2 = [
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "おかえり😊\nChapter2へようこそ♪",
    autoNext: true,
    delay: 600,
  },
  {
    type: "talk",
    character: "ichika",
    face: "thinking",
    text: "今回は「スタート展示」について勉強するよ✨",
    autoNext: true,
    delay: 900,
  },
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "スタート展示は、本番前に選手がどのコースから進入するか、スタートの雰囲気を見るためのものだよ。",
    autoNext: true,
    delay: 900,
  },
  {
    type: "quiz",
    character: "ichika",
    face: "thinking",
    question: "スタート展示で確認するものは？",
    choices: ["進入やスタート", "選手の年齢", "観客数"],
    answer: 0,
    correctText: "正解！\n進入やスタートの雰囲気を見るんだよ🚤✨",
    wrongText: "惜しい！\nスタート展示では進入やスタートを見るよ♪",
  },
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "スタート展示を見ると、本番でコースが変わる可能性にも気づけるよ♪",
    autoNext: true,
    delay: 900,
  },
  {
    type: "quiz",
    character: "ichika",
    face: "thinking",
    question: "進入とは何のこと？",
    choices: ["走るコースに入ること", "配当のこと", "天気のこと"],
    answer: 0,
    correctText: "正解！\nどのコースに入るかを見るのが大事だよ😊",
    wrongText: "惜しい！\n進入は、どのコースに入るかのことだよ。",
  },
  {
    type: "talk",
    character: "ichika",
    face: "happy",
    text: "最後にもう一問だけ♪",
    autoNext: true,
    delay: 900,
  },
  {
    type: "quiz",
    character: "ichika",
    face: "thinking",
    question: "スタート展示は予想に役立つ？",
    choices: ["役立つ", "まったく関係ない", "見てはいけない"],
    answer: 0,
    correctText: "ピンポーン！\n展示を見ると予想のヒントになるよ✨",
    wrongText: "惜しい！\nスタート展示は予想のヒントになるよ♪",
  },
  {
    type: "clear",
    character: "ichika",
    face: "happy",
    text: "MISSION CLEAR！\nスタート展示入門、GETだよ🏅",
  },
];

export default chapter2;
