import Link from "next/link";
import {formatNumber,formatSyncedAt,getCourseName,getCourseRacesByDate,normalizeCourseCode,normalizeDate,normalizeRacerName} from "../../lib/boatstrikersLive";
import s from "../live.module.css";
export const dynamic="force-dynamic";
export default async function Page({params,searchParams}){
 const p=await params,q=await searchParams,code=normalizeCourseCode(p.courseCode),date=normalizeDate(q?.date); if(!code)return <main className={s.page}><section className={s.content}><div className={s.error}><span>⚠️</span><h2>開催場コードが不正です</h2></div></section></main>;
 let races=[],err=null; try{races=await getCourseRacesByDate(date,code);}catch(e){console.error(e);err=e.message;} const name=getCourseName(code),sync=races.map(x=>x.synced_at).filter(Boolean).sort().at(-1);
 return <main className={s.page}><header className={s.hero}><div className={s.inner}><div className={s.top}><Link className={s.pill} href={`/races?date=${date}`}>← 開催場一覧</Link><Link className={s.pill} href="/">ホーム</Link></div><div className={s.title}><div className={s.icon}>🚤</div><div><p className={s.eyebrow}>BOAT RACE {String(code).padStart(2,"0")}</p><h1>{name}</h1><p className={s.desc}>1R〜12R 出走表一覧</p><div className={s.metaRow}><span className={s.meta}>{date}</span><span className={s.meta}>{races.length}レース</span><span className={s.meta}>同期 {formatSyncedAt(sync)}</span></div></div></div></div></header>
 {!!races.length&&<nav className={s.sticky}><div className={s.stickyInner}>{races.map(r=><a key={r.race_no} className={s.jump} href={`#race-${r.race_no}`}><strong>{r.race_no}</strong>R</a>)}</div></nav>}
 <section className={s.content}><div className={s.sectionHead}><div><p>RACE SCHEDULE</p><h2>本日のレース</h2></div><span className={s.badge}>{races.length}R</span></div>
 {err?<div className={s.error}><span>⚠️</span><h2>取得できませんでした</h2><p>{err}</p></div>:!races.length?<div className={s.empty}><span>🚤</span><h2>データがありません</h2><Link className={s.back} href={`/races?date=${date}`}>開催場一覧へ</Link></div>:<div className={s.raceList}>{races.map(r=><article className={s.raceCard} id={`race-${r.race_no}`} key={r.race_no}><div className={s.raceHead}><div className={s.miniNo}><strong>{r.race_no}</strong><span>R</span></div><div className={s.raceText}><h2>{name} {r.race_no}R</h2><p>{r.entries.length}艇・同期 {formatSyncedAt(r.synced_at)}</p></div><span className={`${s.status} ${r.race_status==="exhibition"?s.statusEx:""}`}>{r.race_status==="exhibition"?"展示公開":"出走表公開"}</span></div><div className={s.miniEntries}>{r.entries.map(e=><div className={s.miniEntry} key={e.boat_no}><span className={`${s.boat} ${s[`boat${e.boat_no}`]}`}>{e.boat_no}</span><span className={s.miniName}>{normalizeRacerName(e.racer_name)}</span><span className={s.miniRate}>全国 {formatNumber(e.national_win_rate)}</span></div>)}</div><Link className={s.primary} href={`/races/${String(code).padStart(2,"0")}/${r.race_no}?date=${date}&tab=basic`}><span>出走表・AI新聞を見る</span><span>→</span></Link></article>)}</div>}
 </section></main>;
}
