import crypto from "node:crypto";
import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
export const dynamic="force-dynamic";export const runtime="nodejs";
const TOKEN_SHA="8ba9be2c4bdca06f432f838869131995057bc2f482b8ac0bbf1fba9f4ad133aa";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Supabase環境変数が未設定です");return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}});}
function auth(r){const secret=process.env.CRON_SECRET;if(secret&&r.headers.get("authorization")===`Bearer ${secret}`)return true;const t=r.headers.get("x-supabase-cron-token")||"";if(!t)return false;const d=crypto.createHash("sha256").update(t).digest("hex");return crypto.timingSafeEqual(Buffer.from(d),Buffer.from(TOKEN_SHA));}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function raceUrl(a){return `https://www.boat-strike.online/races/${a.course_code}/${a.race_no}`;}
function innerBreakText(a){return [`🌸【初音・女子イン崩れ理論】`,`${a.course_name||""} ${a.race_no}R`,a.danger_level==="super_danger"?"🌸🌸 超警戒":"🌸 条件成立",`②が①より展示 ${Number(a.exhibition_advantage||0).toFixed(2)}秒速い`,`②が①より1周 ${Number(a.lap_advantage||0).toFixed(2)}秒速い`,a.closing_time?`締切 ${String(a.closing_time).slice(0,5)}`:"","レース詳細を見る",raceUrl(a)].filter(Boolean).join("\n");}
function boxText(a){return [`🎀【初音の箱推し理論】`,`🏁 ${a.course_name||""} ${a.race_no}R`,`①の3着外に注目`,`234 BOX ${a.box_234_rating||"△"}`,`235 BOX ${a.box_235_rating||"△"}`,`345 BOX ${a.box_345_rating||"△"}`,`①勝率 ${a.boat1_win_rate??"—"} / 展示 ${a.boat1_exhibition_rank??"—"}位`,a.closing_time?`締切 ${String(a.closing_time).slice(0,5)}`:"","詳しい出走表はこちら",raceUrl(a)].filter(Boolean).join("\n");}
async function recipients(s,pref){const {data:p,error}=await s.from("bs_member_notification_preferences").select("user_id").eq(pref,true);if(error)throw error;const ids=(p||[]).map(x=>x.user_id).filter(Boolean);if(!ids.length)return[];const {data,error:e}=await s.from("bs_member_profiles").select("line_user_id").in("user_id",ids).eq("membership_status","active").not("line_user_id","is",null);if(e)throw e;return [...new Set((data||[]).map(x=>x.line_user_id).filter(Boolean))];}
async function multicast(ids,text){if(!ids.length)return 0;const token=process.env.LINE_CHANNEL_ACCESS_TOKEN;if(!token)throw new Error("LINE_CHANNEL_ACCESS_TOKEN is not configured");let n=0;for(let i=0;i<ids.length;i+=500){const to=ids.slice(i,i+500),r=await fetch("https://api.line.me/v2/bot/message/multicast",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({to,messages:[{type:"text",text}],notificationDisabled:false})});if(!r.ok){const body=await r.text().catch(()=>"");throw new Error(`LINE multicast failed: ${r.status} ${body}`.trim());}n+=to.length;}return n;}
async function sendTable(s,{table,pref,textBuilder,date}){const {data,error}=await s.from(table).select("*").eq("race_date",date).eq("notified",false).order("detected_at",{ascending:true}).limit(20);if(error)throw error;const ids=await recipients(s,pref),sent=[],failed=[];for(const a of data||[]){try{const n=await multicast(ids,textBuilder(a)),now=new Date().toISOString();const {error:e}=await s.from(table).update({notified:true,notified_at:now,updated_at:now}).eq("id",a.id).eq("notified",false);if(e)throw e;sent.push({id:a.id,recipients:n});}catch(e){failed.push({id:a.id,error:String(e?.message||e)});}}return {pending:(data||[]).length,eligibleRecipients:ids.length,sent,failed};}
export async function GET(request){if(!auth(request))return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{const s=db(),raceDate=today();const [{data:innerInserted,error:innerError},{data:boxInserted,error:boxError}]=await Promise.all([s.rpc("evaluate_hatsune_womens_inner_break_alerts"),s.rpc("evaluate_hatsune_box_alerts")]);if(innerError)throw innerError;if(boxError)throw boxError;const [innerLine,boxLine]=await Promise.all([sendTable(s,{table:"bs_hatsune_womens_inner_break_alerts",pref:"hatsune_venus",textBuilder:innerBreakText,date:raceDate}),sendTable(s,{table:"bs_hatsune_box_alerts",pref:"hatsune_box",textBuilder:boxText,date:raceDate})]);return NextResponse.json({ok:true,raceDate,innerBreak:{inserted:Number(innerInserted||0),line:innerLine},box:{inserted:Number(boxInserted||0),line:boxLine},ranAt:new Date().toISOString()});}catch(e){return NextResponse.json({ok:false,error:e?.message||"hatsune cron failed"},{status:500});}}
