const COURSE_SLUGS = {1:"kiryu",2:"toda",3:"edogawa",4:"heiwajima",5:"tamagawa",6:"hamanako",7:"gamagori",8:"tokoname",9:"tsu",10:"mikuni",11:"biwako",12:"suminoe",13:"amagasaki",14:"naruto",15:"marugame",16:"kojima",17:"miyajima",18:"tokuyama",19:"shimonoseki",20:"wakamatsu",21:"ashiya",22:"fukuoka",23:"karatsu",24:"omura"};

function decodeHtml(text){return String(text||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;/gi,"'").replace(/&quot;/gi,'"');}
function htmlToText(html){return decodeHtml(String(html||"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g,"\n")).replace(/\r/g,"").replace(/[\t ]+/g," ").replace(/\n+/g,"\n").trim();}
function metricOrNull(value){const raw=String(value??"").trim();if(!raw||raw==="-"||raw==="—"||raw==="－")return null;const n=Number(raw);return Number.isFinite(n)?n:null;}
function originalSection(text){const start=text.indexOf("直前情報オリジナル展示");if(start<0)return"";let section=text.slice(start);const sumIndex=section.indexOf("SUM理論");if(sumIndex>=0)section=section.slice(0,sumIndex);const infoIndex=section.indexOf("直前情報について");if(infoIndex>=0)section=section.slice(0,infoIndex);return section;}
function detectOriginalStatus(text,rows){if(rows.length===6)return"published";const section=originalSection(text);if(!section)return"section_not_found";if(section.includes("レース締切予想時刻の15分前に公開されます"))return"not_published";if(/1周\s+回り足\s+直線\s+展示/.test(section.replace(/\n/g," ").replace(/\s+/g," ")))return"parse_failed";return"original_data_unavailable";}
function parseRowsFromText(text){const section=originalSection(text);if(!section)return[];const compact=section.replace(/\n/g," ").replace(/\s+/g," ").trim();const metric="(?:\\d{1,2}\\.\\d{2}|[-—－])";const pattern=new RegExp(`(?:^|\\s)([1-6])\\s+(.{1,50}?)\\s+(A1|A2|B1|B2)\\s+(${metric})\\s+(${metric})\\s+(${metric})\\s+(${metric})(?=\\s|$)`,`g`);const rows=[];for(const match of compact.matchAll(pattern)){const lapTime=metricOrNull(match[4]);const turnTime=metricOrNull(match[5]);const straightTime=metricOrNull(match[6]);const exhibitionTime=metricOrNull(match[7]);if(exhibitionTime===null)continue;rows.push({boatNo:Number(match[1]),racerName:match[2].trim(),class:match[3],lapTime,turnTime,straightTime,exhibitionTime});}return[...new Map(rows.map(r=>[r.boatNo,r])).values()].sort((a,b)=>a.boatNo-b.boatNo);}
function parseStartRowsFromText(text){const start=text.indexOf("スタート情報");if(start<0)return[];let section=text.slice(start);const end=section.indexOf("水面気象情報");if(end>=0)section=section.slice(0,end);const compact=section.replace(/\n/g," ").replace(/\s+/g," ").trim();const pattern=/(?:^|\s)([1-6])\s+([FL]?\.\d{2})(?=\s|$)/g;const rows=[];let course=0;for(const match of compact.matchAll(pattern)){course+=1;const boatNo=Number(match[1]);const raw=match[2].toUpperCase();const symbol=raw.startsWith("F")?"F":raw.startsWith("L")?"L":"";const digits=raw.replace(/[FL]/g,"");const absolute=Number(`0${digits}`);const st=Number.isFinite(absolute)?(symbol==="F"?-absolute:absolute):null;rows.push({boatNo,exhibitionCourse:course,exhibitionSt:st,exhibitionSymbol:symbol});}return[...new Map(rows.map(r=>[r.boatNo,r])).values()];}
function parseWeatherFromText(text){const start=text.indexOf("水面気象情報");if(start<0)return null;let section=text.slice(start);const footer=section.indexOf("BOATERS");if(footer>=0)section=section.slice(0,footer);const compact=section.replace(/\n/g," ").replace(/\s+/g," ").trim();const numberAfter=(label,unit)=>{const unitPart=unit?`\\s*${unit}`:"";const match=compact.match(new RegExp(`${label}\\s+(-?\\d+(?:\\.\\d+)?)${unitPart}`));return match?Number(match[1]):null;};const textAfter=(label)=>{const match=compact.match(new RegExp(`${label}\\s+([^\\s]+)`));return match?match[1].trim():null;};const weather={windSpeed:numberAfter("風速","m/s"),windDirection:textAfter("風向"),weather:textAfter("天候"),airTemperature:numberAfter("気温","℃"),waveHeight:numberAfter("波高","cm"),waterTemperature:numberAfter("水温","℃")};return Object.values(weather).some(value=>value!==null&&value!==undefined&&value!=="")?weather:null;}
export function buildBoatersOriginalTenjiUrl({raceDate,courseCode,raceNo}){const slug=COURSE_SLUGS[Number(courseCode)];if(!slug)throw new Error(`未対応の場コードです: ${courseCode}`);return `https://boaters-boatrace.com/race/${slug}/${raceDate}/${Number(raceNo)}R/last-minute?last-minute-content=original-tenji`;}
function buildCandidateUrls(race){const primary=buildBoatersOriginalTenjiUrl(race);const legacy=primary.replace("/last-minute?","?content=last-minute&");return[primary,legacy];}
async function fetchText(url,timeoutMs){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{cache:"no-store",redirect:"follow",signal:controller.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; BoatStrikers/1.0; +https://www.boat-strike.online/)",accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"ja,en-US;q=0.8,en;q=0.6"}});if(!response.ok)return{ok:false,url,status:response.status,text:""};return{ok:true,url,status:response.status,text:htmlToText(await response.text())};}catch(error){return{ok:false,url,status:null,text:"",error:error?.name==="AbortError"?"timeout":error?.message||"fetch failed"};}finally{clearTimeout(timeout);}}
export async function fetchBoatersOriginalTenji(race,options={}){const timeoutMs=options.timeoutMs||7000;let last={ok:false,url:buildBoatersOriginalTenjiUrl(race),status:null,rows:[],weather:null,published:false,startPublished:false,weatherPublished:false,reason:"fetch_failed"};for(const url of buildCandidateUrls(race)){const fetched=await fetchText(url,timeoutMs);if(!fetched.ok){last={...last,url,status:fetched.status,error:fetched.error||null,reason:fetched.error||`http_${fetched.status||"error"}`};continue;}const text=fetched.text;const exhibitionRows=parseRowsFromText(text);const startRows=parseStartRowsFromText(text);const weather=parseWeatherFromText(text);const startMap=new Map(startRows.map(r=>[r.boatNo,r]));const rows=exhibitionRows.map(row=>({...row,...(startMap.get(row.boatNo)||{})}));const reason=detectOriginalStatus(text,rows);const originalFieldCounts={lap:rows.filter(r=>r.lapTime!==null).length,turn:rows.filter(r=>r.turnTime!==null).length,straight:rows.filter(r=>r.straightTime!==null).length,exhibition:rows.filter(r=>r.exhibitionTime!==null).length};last={ok:rows.length===6,url,status:fetched.status,rows,weather,published:rows.length===6,startPublished:startRows.length===6,weatherPublished:Boolean(weather),reason,originalFieldCounts};if(rows.length===6)return last;if(reason==="not_published")return last;}return last;}
