const COURSE_SLUGS = {1:"kiryu",2:"toda",3:"edogawa",4:"heiwajima",5:"tamagawa",6:"hamanako",7:"gamagori",8:"tokoname",9:"tsu",10:"mikuni",11:"biwako",12:"suminoe",13:"amagasaki",14:"naruto",15:"marugame",16:"kojima",17:"miyajima",18:"tokuyama",19:"shimonoseki",20:"wakamatsu",21:"ashiya",22:"fukuoka",23:"karatsu",24:"omura"};

function decodeHtml(text){return String(text||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;/gi,"'").replace(/&quot;/gi,'"');}
function htmlToText(html){return decodeHtml(String(html||"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g,"\n")).replace(/\r/g,"").replace(/[\t ]+/g," ").replace(/\n+/g,"\n").trim();}
function parseRowsFromText(text){const start=text.indexOf("直前情報オリジナル展示");if(start<0)return[];let section=text.slice(start);const sumIndex=section.indexOf("SUM理論");if(sumIndex>=0)section=section.slice(0,sumIndex);const compact=section.replace(/\n/g," ").replace(/\s+/g," ").trim();const pattern=/(?:^|\s)([1-6])\s+(.{1,40}?)\s+(A1|A2|B1|B2)\s+(\d{1,2}\.\d{2})\s+(\d{1,2}\.\d{2})\s+(\d{1,2}\.\d{2})\s+(\d{1,2}\.\d{2})(?=\s|$)/g;const rows=[];for(const match of compact.matchAll(pattern)){rows.push({boatNo:Number(match[1]),racerName:match[2].trim(),class:match[3],lapTime:Number(match[4]),turnTime:Number(match[5]),straightTime:Number(match[6]),exhibitionTime:Number(match[7])});}return[...new Map(rows.map(r=>[r.boatNo,r])).values()].sort((a,b)=>a.boatNo-b.boatNo);}
function parseStartRowsFromText(text){const start=text.indexOf("スタート情報");if(start<0)return[];let section=text.slice(start);const end=section.indexOf("水面気象情報");if(end>=0)section=section.slice(0,end);const compact=section.replace(/\n/g," ").replace(/\s+/g," ").trim();const pattern=/(?:^|\s)([1-6])\s+([FL]?\.\d{2})(?=\s|$)/g;const rows=[];let course=0;for(const match of compact.matchAll(pattern)){course+=1;const boatNo=Number(match[1]);const raw=match[2].toUpperCase();const symbol=raw.startsWith("F")?"F":raw.startsWith("L")?"L":"";const digits=raw.replace(/[FL]/g,"");const absolute=Number(`0${digits}`);const st=Number.isFinite(absolute)?(symbol==="F"?-absolute:absolute):null;rows.push({boatNo,exhibitionCourse:course,exhibitionSt:st,exhibitionSymbol:symbol});}return[...new Map(rows.map(r=>[r.boatNo,r])).values()];}
function parseWeatherFromText(text){const start=text.indexOf("水面気象情報");if(start<0)return null;let section=text.slice(start);const footer=section.indexOf("BOATERS");if(footer>=0)section=section.slice(0,footer);const compact=section.replace(/\n/g," ").replace(/\s+/g," ").trim();const numberAfter=(label,unit)=>{const unitPart=unit?`\\s*${unit}`:"";const match=compact.match(new RegExp(`${label}\\s+(-?\\d+(?:\\.\\d+)?)${unitPart}`));return match?Number(match[1]):null;};const textAfter=(label)=>{const match=compact.match(new RegExp(`${label}\\s+([^\\s]+)`));return match?match[1].trim():null;};const weather={windSpeed:numberAfter("風速","m/s"),windDirection:textAfter("風向"),weather:textAfter("天候"),airTemperature:numberAfter("気温","℃"),waveHeight:numberAfter("波高","cm"),waterTemperature:numberAfter("水温","℃")};return Object.values(weather).some(value=>value!==null&&value!==undefined&&value!=="")?weather:null;}
export function buildBoatersOriginalTenjiUrl({raceDate,courseCode,raceNo}){const slug=COURSE_SLUGS[Number(courseCode)];if(!slug)throw new Error(`未対応の場コードです: ${courseCode}`);return `https://boaters-boatrace.com/race/${slug}/${raceDate}/${Number(raceNo)}R/last-minute?last-minute-content=original-tenji`;}
export async function fetchBoatersOriginalTenji(race,options={}){const url=buildBoatersOriginalTenjiUrl(race);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),options.timeoutMs||7000);try{const response=await fetch(url,{cache:"no-store",signal:controller.signal,headers:{"user-agent":"BoatStrikers/1.0 (+https://www.boat-strike.online/)",accept:"text/html,application/xhtml+xml"}});if(!response.ok)return{ok:false,url,status:response.status,rows:[]};const html=await response.text();const text=htmlToText(html);const exhibitionRows=parseRowsFromText(text);const startRows=parseStartRowsFromText(text);const weather=parseWeatherFromText(text);const startMap=new Map(startRows.map(r=>[r.boatNo,r]));const rows=exhibitionRows.map(row=>({...row,...(startMap.get(row.boatNo)||{})}));return{ok:rows.length===6,url,status:response.status,rows,weather,published:rows.length===6,startPublished:startRows.length===6,weatherPublished:Boolean(weather)};}catch(error){return{ok:false,url,rows:[],weather:null,published:false,startPublished:false,weatherPublished:false,error:error?.name==="AbortError"?"timeout":error?.message||"fetch failed"};}finally{clearTimeout(timeout);}}
