import { getRadioAdminSupabase } from "./supabaseRadioAdmin";
import { SEMINAR_BUCKET } from "./seminarMagazineDb";

export const ICHIKA_BOOK_SERIES = ["sensei","meikan","data-lab","hatsune-women","hatsune-sensei","hatsune-meikan","hatsune-data-lab","kiina-hole","kiina-sensei","kiina-meikan","kiina-data-lab"];

function cleanPages(value){return Array.isArray(value)?value.map(x=>({page:Number(x?.page),path:String(x?.path||"")})).filter(x=>Number.isInteger(x.page)&&x.page>0&&x.path).sort((a,b)=>a.page-b.page):[];}
function cleanArticle(value={}){return {kicker:String(value.kicker||"詳しい解説").trim(),lead:String(value.lead||"").trim(),sections:(Array.isArray(value.sections)?value.sections:[]).map(x=>({heading:String(x?.heading||"").trim(),body:String(x?.body||"").trim()})).filter(x=>x.heading||x.body).slice(0,12)};}
async function signed(path){if(!path)return"";const {data}=await getRadioAdminSupabase().storage.from(SEMINAR_BUCKET).createSignedUrl(path,3600);return data?.signedUrl||"";}
export async function hydrateIchikaBook(row){const pages=cleanPages(row.page_paths);const urls=await Promise.all(pages.map(async p=>({...p,url:await signed(p.path)})));return {dbId:row.id,id:row.issue_no,number:row.number_label||row.issue_no,title:row.title,summary:row.summary||"",date:row.published_at||row.created_at,cover:urls[0]?.url||"",freePages:urls.map(x=>x.url).filter(Boolean),premiumPageCount:0,article:cleanArticle(row.article)};}
export async function listPublishedIchikaBooks(series){if(!ICHIKA_BOOK_SERIES.includes(series))return[];const now=new Date().toISOString();const {data,error}=await getRadioAdminSupabase().from("ichika_book_issues").select("*").eq("series",series).eq("status","published").or(`published_at.is.null,published_at.lte.${now}`).order("published_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(error){console.error("[character books list]",error);return[];}return Promise.all((data||[]).map(hydrateIchikaBook));}
export async function getPublishedIchikaBook(series,issueNo){if(!ICHIKA_BOOK_SERIES.includes(series))return null;const {data,error}=await getRadioAdminSupabase().from("ichika_book_issues").select("*").eq("series",series).eq("issue_no",issueNo).eq("status","published").maybeSingle();if(error||!data)return null;if(data.published_at&&new Date(data.published_at)>new Date())return null;return hydrateIchikaBook(data);}
export function normalizeIchikaBook(body){const series=ICHIKA_BOOK_SERIES.includes(body.series)?body.series:"sensei";const status=body.status==="published"?"published":"draft";return {series,issue_no:String(body.issue_no||"").trim(),number_label:String(body.number_label||"").trim(),title:String(body.title||"").trim(),summary:String(body.summary||"").trim(),page_paths:cleanPages(body.page_paths),article:cleanArticle(body.article),status,published_at:status==="published"?(body.published_at||new Date().toISOString()):(body.published_at||null),updated_at:new Date().toISOString()};}
