export const PROGRAM_PRESETS = [
  {
    key: "",
    label: "プリセットを使わず手動入力",
    title: "",
    url: "",
    contentType: "other",
    host: "BoatStrikers",
    iconText: "番",
    accent: "#168bc7",
  },
  {
    key: "minamo_school",
    label: "私立みなも学園～ふなけん研究部～",
    title: "私立みなも学園～ふなけん研究部～",
    url: "https://www.boat-strike.online/comic",
    contentType: "short",
    host: "3人",
    iconUrl: "/schedule-icons/minamo-school.png",
    iconText: "学",
    accent: "#19a4d8",
  },
  {
    key: "ichika_sensei",
    label: "教えて！一果センセー！",
    title: "教えて！一果センセー！",
    url: "https://www.boat-strike.online/ichika-sensei",
    contentType: "short",
    host: "一果",
    iconUrl: "/schedule-icons/ichika-sensei.png",
    iconText: "先",
    accent: "#168a61",
  },
  {
    key: "ichika_radio",
    label: "一果のボート・ナイト・ニッポン",
    title: "一果のボート・ナイト・ニッポン",
    url: "https://www.boat-strike.online/radio",
    contentType: "radio",
    host: "一果",
    iconUrl: "/schedule-icons/ichika-boat-night.png",
    iconText: "一",
    accent: "#176448",
  },
  {
    key: "hatsune_radio",
    label: "初音のボート・ナイト・ニッポン",
    title: "初音のボート・ナイト・ニッポン",
    url: "https://www.boat-strike.online/radio",
    contentType: "radio",
    host: "初音",
    iconUrl: "/schedule-icons/hatsune-boat-night.png",
    iconText: "初",
    accent: "#8455ca",
  },
  {
    key: "kiina_radio",
    label: "キイナのボート・ナイト・ニッポン",
    title: "キイナのボート・ナイト・ニッポン",
    url: "https://www.boat-strike.online/radio",
    contentType: "radio",
    host: "キイナ",
    iconUrl: "/schedule-icons/kiina-boat-night.png",
    iconText: "キ",
    accent: "#f3a300",
  },
  {
    key: "ichika_seminar",
    label: "一果のイン逃げ鉄板ゼミ",
    title: "一果のイン逃げ鉄板ゼミ",
    url: "https://www.boat-strike.online/library/ichika-seminar",
    contentType: "note",
    host: "一果",
    iconUrl: "/schedule-icons/ichika-seminar.png",
    iconText: "一",
    accent: "#168a61",
  },
  {
    key: "hatsune_seminar",
    label: "初音の女子戦攻略マガジン",
    title: "初音の女子戦攻略マガジン",
    url: "https://www.boat-strike.online/library/hatsune-seminar",
    contentType: "note",
    host: "初音",
    iconUrl: "/schedule-icons/hatsune-seminar.png",
    iconText: "初",
    accent: "#8455ca",
  },
  {
    key: "kiina_seminar",
    label: "キイナの穴党塾",
    title: "キイナの穴党塾",
    url: "https://www.boat-strike.online/library/kiina-seminar",
    contentType: "note",
    host: "キイナ",
    iconUrl: "/schedule-icons/kiina-seminar.png",
    iconText: "キ",
    accent: "#f3a300",
  },
  {
    key: "stadium_notes",
    label: "24場攻略ノート",
    title: "24場攻略ノート",
    url: "https://www.boat-strike.online/library/stadiums",
    contentType: "note",
    host: "BoatStrikers",
    iconUrl: "/schedule-icons/stadium-notes.png",
    iconText: "24",
    accent: "#176bb8",
  },
];

export function getProgramPresetByKey(key) {
  return PROGRAM_PRESETS.find((preset) => preset.key === key) || null;
}

export function getProgramPresetByTitle(title) {
  const normalized = String(title || "").trim();
  return PROGRAM_PRESETS.find((preset) => preset.title === normalized) || null;
}
