import { verifyNationalBeforeInfo } from './nationalBeforeInfoIdentity.js';
const SOURCE='toda_official_verified', LABEL='BOAT RACE戸田公式';
const clean=v=>String(v||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/[\s\u3000]+/g,' ').trim();
const fail=error=>({ok:false,supported:true,published:false,source:SOURCE,sourceLabel:LABEL,rows:[],error});
const tag=(xml,name)=>clean(String(xml||'').match(new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]||'');
const records=xml=>[...String(xml||'').matchAll(/<record\b[^>]*>([\s\S]*?)<\/record>/gi)].map(m=>m[1]);
const timing=(v,min,max)=>{const s=clean(v);if(!/^\d{1,2}\.\d{2}$/.test(s))return null;const n=Number(s);return n>=min&&n<=max?n:null;};
export function validTodaRace(race){const n=Number(race?.raceNo),d=String(race?.raceDate||'');return Number(race?.courseCode)===2&&Number.isInteger(n)&&n>=1&&n<=12&&/^20\d{2}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;}
function roster(xml){if(tag(xml,'jcd')!=='02')return {ok:false,error:'source_venue_mismatch'};const rows=records(xml).map(r=>({boatNo:Number(tag(r,'teiban')),racerNo:tag(r,'toban')})).filter(r=>r.boatNo>=1&&r.boatNo<=6).sort((a,b)=>a.boatNo-b.boatNo);if(rows.length!==6||rows.some((r,i)=>r.boatNo!==i+1||!/^\d{4}$/.test(r.racerNo))||new Set(rows.map(r=>r.racerNo)).size!==6)return {ok:false,error:'six_unique_boats_required'};return {ok:true,rows};}
export function parseTodaOriginal(originalXml,rosterXml,race){if(!validTodaRace(race))return fail('invalid_race');const r=roster(rosterXml);if(!r.ok)return fail(r.error);const source=records(originalXml);if(source.length!==6)return fail(source.length?'six_unique_boats_required':'official_original_tenji_not_available');const rows=source.map((x,i)=>{const boatNo=tag(x,'teiban')?Number(tag(x,'teiban')):i+1;return {boatNo,racerNo:r.rows.find(y=>y.boatNo===boatNo)?.racerNo||null,exhibitionTime:timing(tag(x,'ttime'),6,8),lapTime:timing(tag(x,'rnd'),30,45),turnTime:timing(tag(x,'cnr'),4,10),straightTime:timing(tag(x,'str'),4,10)};}).sort((a,b)=>a.boatNo-b.boatNo);if(rows.length!==6||rows.some((x,i)=>x.boatNo!==i+1||!x.racerNo||[x.exhibitionTime,x.lapTime,x.turnTime,x.straightTime].some(v=>v===null)))return fail('measurements_incomplete_or_invalid');return {ok:true,supported:true,published:true,source:SOURCE,sourceLabel:LABEL,rows};}
export function verifyToda(originalXml,rosterXml,referenceHtml,race){const parsed=parseTodaOriginal(originalXml,rosterXml,race);if(!parsed.ok)return parsed;const reference=verifyNationalBeforeInfo(referenceHtml,race);if(!reference.ok)return fail(reference.error||'reference_unavailable');for(const row of parsed.rows){const match=reference.rows.find(x=>x.boatNo===row.boatNo&&x.racerNo===row.racerNo);if(!match||match.exhibitionTime!==row.exhibitionTime)return fail('roster_or_exhibition_mismatch');}return {...parsed,identity:{verified:true,courseCode:2,raceDate:race.raceDate,raceNo:Number(race.raceNo),evidence:'fixed_date_race_xml_roster_and_six_boat_exhibition_match_national_beforeinfo'},eligibleTheories:{ichika:true,hatsune:true,kiina:true},availableMetrics:['exhibition','lap','turn','straight']};}
async function read(url,options={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),Math.min(18000,Math.max(1000,Number(options.timeoutMs)||15000)));try{const response=await fetch(url,{cache:'no-store',redirect:'manual',signal:c.signal,headers:{'user-agent':'BoatStrikers/1.0 (+https://www.boat-strike.online/)',referer:'https://www.boatrace-toda.jp/'}});if(!response.ok){await response.body?.cancel();return {ok:false,error:'upstream_http_error',status:response.status};}const body=await response.text();return body.trim()?{ok:true,body}:{ok:false,error:'exhibition_pending',status:response.status};}catch(error){return {ok:false,error:error?.name==='AbortError'?'upstream_timeout':'upstream_fetch_failed'};}finally{c.abort();clearTimeout(timer);}}
export async function fetchTodaVerifiedOriginalTenji(race,options={}){if(!validTodaRace(race))return fail('invalid_race');const day=race.raceDate.replaceAll('-',''),no=String(Number(race.raceNo)).padStart(2,'0'),base=`https://www.boatrace-toda.jp/xml/kaisai/${day}`,url=`${base}/race_table_original_${no}.xml`,rosterUrl=`${base}/race_table_${no}.xml`,referenceUrl=`https://www.boatrace.jp/owpc/pc/race/beforeinfo?rno=${Number(race.raceNo)}&jcd=02&hd=${day}`;const [original,raceRoster,reference]=await Promise.all([read(url,options),read(rosterUrl,options),read(referenceUrl,options)]);for(const result of [original,raceRoster,reference])if(!result.ok)return {...fail(result.error),status:result.status,url,rosterUrl,referenceUrl};return {...verifyToda(original.body,raceRoster.body,reference.body,race),url,rosterUrl,referenceUrl};}
