import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { evaluateDailyRace, mapDailyEntry } from "../../../lib/dailyNewspaperEvaluator";

export const dynamic="force-dynamic";
const COURSE_CODES={"桐生":1,"戸田":2,"江戸川":3,"平和島":4,"多摩川":5,"浜名湖":6,"蒲郡":7,"常滑":8,"津":9,"三国":10,"びわこ":11,"住之江":12,"尼崎":13,"鳴門":14,"丸亀":15,"児島":16,"宮島":17,"徳山":18,"下関":19,"若松":20,"芦屋":21,"福岡":22,"唐津":23,"大村":24};
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null;}
function summary(character,rows){const picks=rows.filter(r=>r.eligible&&r.mark!=="見"&&r.confidence).sort((a,b)=>parseFloat(b.confidence)-parseFloat(a.confidence));if(!picks.length)return {points:"この開催場では強い候補を抽出できませんでした。",targets:"見送り",closing:character==="ichika"?"今日は無理にインを追わず、条件が整うレースを待とう♪":character==="kiina"?"穴は待つのも勝負！数字が弱い日は無理に5号艇を追わないよ⚡":"条件の合う女子戦を丁寧に見ていこう♡"};const top=picks.slice(0,3),best=top[0],targets=top.map(r=>r.race).join("・");if(character==="ichika")return {points:`イン逃げ評価の上位は${targets}。最注目は${best.race}（${best.confidence}）。`,targets,closing:`今日は${best.race}が一果の最注目！インの条件を確認して、無理に広げず狙っていこう♪`};if(character==="kiina")return {points:`5号艇1着期待の上位は${targets}。最注目は${best.race}（${best.confidence}）。`,targets,closing:`キイナは${best.race}に注目！5号艇の数字が強いところから穴を狙うよ⚡`};return {points:`女子戦評価の上位は${targets}。最注目は${best.race}（${best.confidence}）。`,targets,closing:`今日は${best.race}が初音の注目レース♡ 女子戦の強弱を見ながら狙いどころを絞ろう！`};}
export async function GET(req){const {searchParams}=new URL(req.url),date=searchParams.get("date")||"",course=searchParams.get("course")||"",character=searchParams.get("character")||"ichika",edition=searchParams.get("edition")||"前日版",code=COURSE_CODES[course];if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!code||!["ichika","hatsune","kiina"].includes(character))return NextResponse.json({error:"invalid_request"},{status:400});const db=client();if(!db)return NextResponse.json({error:"supabase_not_configured"},{status:500});const timing=edition==="前日版"?"previous_day":"after_exhibition";const [ev,en]=await Promise.all([db.from("bs_race_events").select("*").eq("race_date",date).eq("course_code",code).order("race_no"),db.from("bs_race_entries").select("*").eq("race_date",date).eq("course_code",code).order("race_no").order("boat_no")]);if(ev.error)return NextResponse.json({error:ev.error.message},{status:500});if(en.error)return NextResponse.json({error:en.error.message},{status:500});if(!(ev.data||[]).length)return NextResponse.json({date,course,character,timing,eventCount:0,rows:[],points:"",targets:"",closing:"",message:`${date}の${course}には開催データがありません。`});const byRace=new Map();for(const raw of en.data||[]){const e=mapDailyEntry(raw),n=Number(e.race_no);if(!byRace.has(n))byRace.set(n,[]);byRace.get(n).push(e);}const eventMap=new Map((ev.data||[]).map(e=>[Number(e.race_no),e]));const rows=Array.from({length:12},(_,i)=>{const n=i+1,event=eventMap.get(n),entries=byRace.get(n)||[];if(!event)return {race:`${n}R`,eligible:false,mark:"見",main:"",bet:"",confidence:"",comment:"開催データなし"};return {race:`${n}R`,...evaluateDailyRace({event,entries,character,timing})};});return NextResponse.json({date,course,character,timing,eventCount:(ev.data||[]).length,entryCount:(en.data||[]).length,rows,...summary(character,rows)});}
