"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

const card={border:"1px solid #f1cfe0",borderRadius:18,background:"#fff",padding:18};
const label={color:"#718096",fontSize:13};
const td={padding:"11px 8px",borderBottom:"1px solid #f7e8ef",fontSize:14};
const navButton={padding:"10px 12px",borderRadius:10,border:"1px solid #e8bfd3",background:"#fff"};
function pct(v){return v==null?"—":`${(Number(v)*100).toFixed(1)}%`;}
function formatTime(v){return v?String(v).slice(0,5):"—";}
function rankLabel(v){const n=Number(v);return Number.isFinite(n)&&n>0?`${n}着`:"結果待ち";}
function todayJst(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function shiftDate(date,days){const d=new Date(`${date}T00:00:00+09:00`);d.setDate(d.getDate()+days);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}

export default function HatsuneWomensInnerBreakPage(){
  const [payload,setPayload]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[soundOn,setSoundOn]=useState(false),[date,setDate]=useState(todayJst()),[mode,setMode]=useState("day");
  const knownIds=useRef(new Set()),initialized=useRef(false);
  const playAlert=useCallback(()=>{if(!soundOn)return;try{const AudioContext=window.AudioContext||window.webkitAudioContext;const ctx=new AudioContext();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.frequency.value=820;gain.gain.setValueAtTime(.15,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.6);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.6);}catch{}},[soundOn]);
  const load=useCallback(async()=>{try{const qs=new URLSearchParams({date,mode});const res=await fetch(`/api/admin/hatsune-womens-inner-break?${qs}`,{cache:"no-store"});const json=await res.json();if(!res.ok||!json.ok)throw new Error(json.error||"取得失敗");if(mode==="day"&&date===todayJst()){const next=new Set((json.alerts||[]).map(x=>x.id));if(initialized.current&&(json.alerts||[]).some(x=>!knownIds.current.has(x.id)))playAlert();knownIds.current=next;initialized.current=true;}setPayload(json);setError("");}catch(e){setError(e?.message||"取得に失敗しました");}finally{setLoading(false);}},[date,mode,playAlert]);
  useEffect(()=>{setLoading(true);load();const id=setInterval(load,10000);return()=>clearInterval(id);},[load]);
  async function runNow(){setLoading(true);try{const res=await fetch("/api/admin/hatsune-womens-inner-break",{method:"POST"});const json=await res.json().catch(()=>({}));if(!res.ok||!json.ok)throw new Error(json.error||"判定に失敗しました");await load();}catch(e){setError(e?.message||"判定に失敗しました");}finally{setLoading(false);}}
  const stats=payload?.stats||{},allStats=payload?.allStats||{},alerts=payload?.alerts||[],daily=payload?.daily||[];
  const summary=useMemo(()=>{const s=mode==="all"?allStats:stats;return `成立${s.matched??0}R / ①1着${s.first??0}R / ①1着率${pct(s.firstRate)}`;},[mode,stats,allStats]);
  return <main style={{minHeight:"100vh",background:"#fff7fb",padding:"28px 16px 56px",color:"#102033"}}><div style={{maxWidth:1120,margin:"0 auto"}}>
    <div style={{display:"flex",gap:16,justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",marginBottom:20}}><div><div style={{fontSize:13,fontWeight:800,letterSpacing:".12em",color:"#b43d78"}}>BOATSTRIKERS / HATSUNE ALERT</div><h1 style={{margin:"6px 0 8px",fontSize:30}}>🌸 初音・女子イン崩れ理論</h1><p style={{margin:0,color:"#617184"}}>女子戦で②の展示・1周が①を明確に上回るレースを検知します。</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>setSoundOn(v=>!v)} style={navButton}>{soundOn?"🔊 通知音 ON":"🔇 通知音 OFF"}</button><button onClick={runNow} disabled={loading} style={{padding:"11px 14px",borderRadius:12,border:0,background:"#c9407c",color:"#fff",fontWeight:800}}>{loading?"確認中…":"今すぐ判定"}</button></div></div>
    <section style={{...card,marginBottom:20,background:"#fffafd"}}><div style={{fontWeight:900,marginBottom:8}}>現在の通知条件</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{["女子戦限定","②が①より展示0.05秒以上速い","②が①より1周0.10秒以上速い","②③とも成立なら超警戒"].map(x=><span key={x} style={{padding:"7px 10px",borderRadius:999,background:"#fde6f1",color:"#9e2f65",fontSize:13,fontWeight:800}}>{x}</span>)}</div></section>
    {error?<div style={{...card,borderColor:"#f0b7b7",color:"#a12",marginBottom:16}}>{error}</div>:null}
    <section style={{...card,marginBottom:20}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><button onClick={()=>setMode("day")} style={{...navButton,background:mode==="day"?"#c9407c":"#fff",color:mode==="day"?"#fff":"#102033"}}>日付別</button><button onClick={()=>setMode("all")} style={{...navButton,background:mode==="all"?"#c9407c":"#fff",color:mode==="all"?"#fff":"#102033"}}>全期間</button>{mode==="day"&&<><button onClick={()=>setDate(d=>shiftDate(d,-1))} style={navButton}>← 前日</button><input type="date" value={date} onChange={e=>setDate(e.target.value)} style={{padding:"9px 12px",borderRadius:10,border:"1px solid #e8bfd3",fontWeight:700}}/><button onClick={()=>setDate(d=>shiftDate(d,1))} style={navButton}>翌日 →</button><button onClick={()=>setDate(todayJst())} style={navButton}>今日</button></>}<span style={{marginLeft:"auto",color:"#718096",fontSize:13}}>{summary}</span></div></section>
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,marginBottom:20}}><div style={card}><div style={label}>成立</div><strong style={{fontSize:30}}>{stats.matched??"—"}</strong></div><div style={card}><div style={label}>①1着率</div><strong style={{fontSize:30,color:"#c9407c"}}>{pct(stats.firstRate)}</strong></div><div style={card}><div style={label}>①2連対率</div><strong style={{fontSize:30}}>{pct(stats.top2Rate)}</strong></div><div style={card}><div style={label}>①3連対率</div><strong style={{fontSize:30}}>{pct(stats.top3Rate)}</strong></div></section>
    {mode==="day"&&<section style={{...card,marginBottom:20}}><h2 style={{margin:"0 0 5px",fontSize:20}}>成立履歴</h2><div style={{color:"#718096",fontSize:13,marginBottom:14}}>{date} / 10秒ごとに自動更新</div>{!alerts.length?<div style={{padding:"30px 0",color:"#718096"}}>この日の成立レースはありません。</div>:<AlertList alerts={alerts}/>}</section>}
    <section style={{...card,marginBottom:20}}><h2 style={{margin:"0 0 14px",fontSize:20}}>📅 日別実績</h2>{!daily.length?<div style={{padding:"20px 0",color:"#718096"}}>履歴がありません。</div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:620}}><thead><tr>{["日付","成立","①1着","①1着率","①2連対率","①3連対率"].map(h=><th key={h} style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid #ead5df",fontSize:12,color:"#718096"}}>{h}</th>)}</tr></thead><tbody>{daily.map(d=><tr key={d.date} onClick={()=>{setDate(d.date);setMode("day");}} style={{cursor:"pointer"}}><td style={td}><strong>{d.date}</strong></td><td style={td}>{d.matched}R</td><td style={td}>{d.first}R</td><td style={td}>{pct(d.firstRate)}</td><td style={td}>{pct(d.top2Rate)}</td><td style={td}>{pct(d.top3Rate)}</td></tr>)}</tbody></table></div>}</section>
    {mode==="all"&&<section style={card}><h2 style={{margin:"0 0 14px",fontSize:20}}>全期間の成立レース</h2>{!alerts.length?<div style={{padding:"30px 0",color:"#718096"}}>履歴がありません。</div>:<AlertList alerts={alerts} showDate/>}</section>}
  </div></main>;
}

function AlertList({alerts,showDate=false}){return <div style={{display:"grid",gap:10}}>{alerts.map(a=><article key={a.id} style={{border:"1px solid #efd2e0",borderRadius:14,padding:14,display:"grid",gridTemplateColumns:"minmax(150px,1.35fr) repeat(4,minmax(105px,1fr))",gap:12,alignItems:"center",background:"#fffafd"}}><div><strong style={{fontSize:18}}>{a.course_name||`場${a.course_code}`} {a.race_no}R</strong><div style={{marginTop:4,color:"#718096",fontSize:13}}>{showDate?`${a.race_date} / `:""}締切 {formatTime(a.closing_time)}</div><div style={{marginTop:5,fontSize:12,fontWeight:900,color:a.danger_level==="super_danger"?"#b0004b":"#c9407c"}}>{a.danger_level==="super_danger"?"🌸🌸 超警戒":"🌸 警戒"}</div></div><div><div style={label}>展示差</div><strong>②が {Number(a.exhibition_advantage||0).toFixed(2)}秒速い</strong></div><div><div style={label}>1周差</div><strong>②が {Number(a.lap_advantage||0).toFixed(2)}秒速い</strong></div><div><div style={label}>①展示 / ②展示</div><strong>{a.boat1_exhibition??"—"} / {a.boat2_exhibition??"—"}</strong></div><div><div style={label}>①結果</div><strong>{rankLabel(a.result_rank)}</strong></div></article>)}</div>;}
