"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "./magazineAdmin.module.css";

const SECTION_TYPES = [
  ["intro","今回の結論"],["comic","漫画"],["ichika","一果のイン逃げ鉄板ゼミ"],
  ["hatsune","初音の女子戦研究室"],["kiina","キイナの穴党塾"],["ai","AI研究室"],
  ["example","実例レース"],["checklist","チェックリスト"],["summary","まとめ・次号予告"],["free","自由ページ"]
];
const EMPTY={id:null,slug:"",volume:"Vol.001",title:"",subtitle:"",summary:"",cover_image_url:"",theme_color:"#0c3f78",accent_color:"#ff4f87",status:"draft",published_at:"",sections:[]};
function block(type="free"){const label=SECTION_TYPES.find(x=>x[0]===type)?.[1]||"自由ページ";return {id:crypto.randomUUID(),type,title:label,kicker:"",body:"",image_url:"",caption:"",points:[""],table_rows:[],next_issue:""};}
function toLocal(v){if(!v)return"";const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function payload(issue){return {...issue,published_at:issue.published_at?new Date(issue.published_at).toISOString():null}}
export default function MagazineAdminClient(){
 const [issues,setIssues]=useState([]),[issue,setIssue]=useState(EMPTY),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch('/api/admin/magazine/issues',{cache:'no-store'});if(r.status===401){location.href='/admin/radio-blog/login';return}const j=await r.json();if(r.ok)setIssues(j.issues||[]);else setMessage(j.error||'取得できませんでした。')},[]);
 useEffect(()=>{load()},[load]);
 function fresh(){setIssue({...EMPTY,sections:[block('intro'),block('comic'),block('ichika'),block('hatsune'),block('kiina'),block('ai'),block('example'),block('checklist'),block('summary')]});setMessage('');scrollTo({top:0,behavior:'smooth'})}
 function edit(row){setIssue({...row,cover_image_url:row.cover_image_url||'',published_at:toLocal(row.published_at),sections:(row.sections||[]).map(s=>({...s,id:s.id||crypto.randomUUID(),points:Array.isArray(s.points)?s.points:[""],table_rows:Array.isArray(s.table_rows)?s.table_rows:[]}))});scrollTo({top:0,behavior:'smooth'})}
 function field(k,v){setIssue(x=>({...x,[k]:v}))}
 function section(i,patch){setIssue(x=>({...x,sections:x.sections.map((s,n)=>n===i?{...s,...patch}:s)}))}
 function add(type){setIssue(x=>({...x,sections:[...x.sections,block(type)]}))}
 function remove(i){setIssue(x=>({...x,sections:x.sections.filter((_,n)=>n!==i)}))}
 function move(i,d){const n=i+d;if(n<0||n>=issue.sections.length)return;setIssue(x=>{const a=[...x.sections];[a[i],a[n]]=[a[n],a[i]];return {...x,sections:a}})}
 async function upload(file,done){if(!file)return;setBusy(true);setMessage('画像をアップロード中…');const f=new FormData();f.append('file',file);const r=await fetch('/api/admin/magazine/upload',{method:'POST',body:f});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.error||'アップロード失敗');return}done(j.url);setMessage('画像をアップロードしました。')}
 async function save(e){e.preventDefault();setBusy(true);setMessage('');const endpoint=issue.id?`/api/admin/magazine/issues/${issue.id}`:'/api/admin/magazine/issues';const r=await fetch(endpoint,{method:issue.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(issue))});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.error||'保存に失敗しました。');return}setIssue({...j.issue,cover_image_url:j.issue.cover_image_url||'',published_at:toLocal(j.issue.published_at)});setMessage('雑誌を保存しました。');load()}
 async function del(){if(!issue.id||!confirm('この雑誌を削除しますか？'))return;const r=await fetch(`/api/admin/magazine/issues/${issue.id}`,{method:'DELETE'});if(r.ok){fresh();load()}else setMessage('削除に失敗しました。')}
 return <>
  <header className={styles.header}><div><span>BOATSTRIKERS CMS</span><h1>雑誌管理</h1><p>入力した内容を、統一されたWeb雑誌レイアウトへ自動変換します。</p></div><div className={styles.headerActions}><a href="/library/weekly" target="_blank">公開ページを見る</a><button type="button" onClick={fresh}>＋ 新しい号</button></div></header>
  <form onSubmit={save} className={styles.editor}>
   <section className={styles.panel}><h2>1. 基本情報・表紙</h2><div className={styles.grid3}><label>URL名<input value={issue.slug} onChange={e=>field('slug',e.target.value)} placeholder="vol-001" required/></label><label>号数<input value={issue.volume} onChange={e=>field('volume',e.target.value)} /></label><label>公開状態<select value={issue.status} onChange={e=>field('status',e.target.value)}><option value="draft">下書き</option><option value="published">公開</option></select></label></div><label>大見出し<input value={issue.title} onChange={e=>field('title',e.target.value)} placeholder="インが飛ぶ条件7選" required/></label><label>サブタイトル<input value={issue.subtitle} onChange={e=>field('subtitle',e.target.value)} /></label><label>一覧用紹介文<textarea rows="3" value={issue.summary} onChange={e=>field('summary',e.target.value)}/></label><div className={styles.grid3}><label>公開日時<input type="datetime-local" value={issue.published_at} onChange={e=>field('published_at',e.target.value)}/></label><label>テーマ色<input type="color" value={issue.theme_color} onChange={e=>field('theme_color',e.target.value)}/></label><label>アクセント色<input type="color" value={issue.accent_color} onChange={e=>field('accent_color',e.target.value)}/></label></div><div className={styles.imageField}><div>{issue.cover_image_url?<img src={issue.cover_image_url} alt="表紙"/>:<span>表紙画像</span>}</div><label className={styles.upload}>表紙画像を選択<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],url=>field('cover_image_url',url))}/></label><input value={issue.cover_image_url} onChange={e=>field('cover_image_url',e.target.value)} placeholder="画像URLを直接入力してもOK"/></div></section>
   <section className={styles.panel}><div className={styles.sectionHead}><div><h2>2. 誌面ブロック</h2><p>並び順がそのまま誌面の目次・表示順になります。</p></div><select onChange={e=>{if(e.target.value)add(e.target.value);e.target.value=''}} defaultValue=""><option value="">＋ コーナー追加</option>{SECTION_TYPES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>
   <div className={styles.blocks}>{issue.sections.map((s,i)=><article className={styles.block} key={s.id||i}><div className={styles.blockBar}><b>{String(i+1).padStart(2,'0')}　{SECTION_TYPES.find(x=>x[0]===s.type)?.[1]||'自由ページ'}</b><div><button type="button" onClick={()=>move(i,-1)}>↑</button><button type="button" onClick={()=>move(i,1)}>↓</button><button type="button" onClick={()=>remove(i)}>削除</button></div></div><div className={styles.grid2}><label>コーナー種別<select value={s.type} onChange={e=>section(i,{type:e.target.value})}>{SECTION_TYPES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>小見出し<input value={s.kicker||''} onChange={e=>section(i,{kicker:e.target.value})} placeholder="今週のテーマ"/></label></div><label>見出し<input value={s.title||''} onChange={e=>section(i,{title:e.target.value})}/></label><label>本文<textarea rows="6" value={s.body||''} onChange={e=>section(i,{body:e.target.value})} placeholder="改行すると、そのまま段落として表示されます。"/></label><div className={styles.imageField}><div>{s.image_url?<img src={s.image_url} alt="誌面"/>:<span>コーナー画像</span>}</div><label className={styles.upload}>画像を選択<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],url=>section(i,{image_url:url}))}/></label><input value={s.image_url||''} onChange={e=>section(i,{image_url:e.target.value})} placeholder="画像URL"/></div><label>画像キャプション<input value={s.caption||''} onChange={e=>section(i,{caption:e.target.value})}/></label><label>ポイント（1行に1項目）<textarea rows="4" value={(s.points||[]).join('\n')} onChange={e=>section(i,{points:e.target.value.split('\n')})} placeholder={'展示順位を確認\nSTは.15以内か？\n風向き・風速を見る'}/></label>{s.type==='summary'&&<label>次号予告<input value={s.next_issue||''} onChange={e=>section(i,{next_issue:e.target.value})}/></label>}</article>)}</div></section>
   <div className={styles.sticky}><span>{message}</span><a className={styles.preview} href={issue.slug?`/library/weekly/${issue.slug}`:'/library/weekly'} target="_blank">プレビュー</a>{issue.id&&<button type="button" className={styles.delete} onClick={del}>削除</button>}<button disabled={busy}>{busy?'保存中…':'雑誌を保存'}</button></div>
  </form>
  <section className={styles.list}><h2>登録済みの雑誌</h2>{issues.length===0?<p>まだ登録がありません。</p>:issues.map(x=><article key={x.id}><div>{x.cover_image_url?<img src={x.cover_image_url} alt=""/>:<span>BOOK</span>}</div><section><small>{x.volume}・{x.status==='published'?'公開中':'下書き'}</small><h3>{x.title}</h3><p>{x.summary}</p></section><button onClick={()=>edit(x)}>編集</button></article>)}</section>
 </>
}
