import Link from "next/link";
import { createClient } from "@supabase/supabase-js";
import { cookies } from "next/headers";
import { getMemberEntitlementFromToken, MEMBER_ACCESS_COOKIE } from "../../lib/memberEntitlement";
import { getCoursesForRacesIndex } from "../lib/racesIndexLight";
import styles from "./today.module.css";
import visualStyles from "./todayVisual.module.css";
import { getPublishedNewspapers } from "../../lib/newspapers";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const metadata={title:"BoatStrikers TODAY｜今日のボートレース情報",description:"今日の開催場、次レース、誕生日選手、グレード戦、3人の新聞、DATA LABをまとめたBoatStrikersのデイリーホームです。",alternates:{canonical:"/today"}};

const COURSE_NAMES={1:"桐生",2:"戸田",3:"江戸川",4:"平和島",5:"多摩川",6:"浜名湖",7:"蒲郡",8:"常滑",9:"津",10:"三国",11:"びわこ",12:"住之江",13:"尼崎",14:"鳴門",15:"丸亀",16:"児島",17:"宮島",18:"徳山",19:"下関",20:"若松",21:"芦屋",22:"福岡",23:"唐津",24:"大村"};
const CHARACTERS=[
 {key:"ichika",name:"一果",emoji:"🌿",role:"イン逃げ担当",copy:"1号艇とイン逃げをデータからチェック",tone:"ichika",href:"/ichika"},
 {key:"hatsune",name:"初音",emoji:"💜",role:"女子戦担当",copy:"女子戦の流れと注目レースをチェック",tone:"hatsune",href:"/hatsune"},
 {key:"kiina",name:"キイナ",emoji:"💛",role:"穴狙い担当",copy:"5アタマを中心に穴の気配をチェック",tone:"kiina",href:"/kiina"},
];
function jstToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function formatDate(date){const [y,m,d]=date.split("-");return `${y}年${Number(m)}月${Number(d)}日`;}
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
function raceHref(code,race,date){return `/races/${Number(code)}/${Number(race)}?date=${date}`;}
async function loadTodayData(date){const client=db();if(!client)return {grades:[],birthdays:[]};const [grade,birthday]=await Promise.all([client.from("bs_grade_race_events").select("start_date,end_date,course_code,grade,title").lte("start_date",date).gte("end_date",date).order("course_code"),client.rpc("bs_today_birthday_racers",{p_date:date})]);return {grades:grade.data||[],birthdays:birthday.data||[]};}
async function memberState(){try{const store=await cookies();const token=store.get(MEMBER_ACCESS_COOKIE)?.value||"";if(!token)return {authenticated:false};return await getMemberEntitlementFromToken(token);}catch{return {authenticated:false};}}

export default async function TodayPage(){
 const displayDate=jstToday();
 const [data,member,todayPapers,courses]=await Promise.all([loadTodayData(displayDate),memberState(),getPublishedNewspapers({date:displayDate,limit:30}),getCoursesForRacesIndex(displayDate).catch(()=>[])]);
 const gradeLabels=new Set(["SG","PG1","G1","G2","G3"]);const grades=data.grades.filter(x=>gradeLabels.has(String(x.grade||"").toUpperCase()));
 const birthdayMap=new Map();for(const row of data.birthdays||[]){const key=row.registration_no;if(!birthdayMap.has(key))birthdayMap.set(key,{...row,races:[]});birthdayMap.get(key).races.push({course_code:row.course_code,race_no:row.race_no,boat_no:row.boat_no});}const birthdayRacers=[...birthdayMap.values()];
 const totalRaces=courses.reduce((n,c)=>n+Number(c.raceCount||0),0);const finishedRaces=courses.reduce((n,c)=>n+Number(c.resultCount||0),0);const liveCourses=courses.filter(c=>c.liveStatus==="live"||c.liveStatus==="exhibition").length;
 const paperByCharacter=new Map();for(const p of todayPapers){if(!paperByCharacter.has(p.character_key))paperByCharacter.set(p.character_key,p);}
 return <main className={`${styles.page} ${visualStyles.page}`} data-page="today">
  <section className={styles.hero} aria-label={`${formatDate(displayDate)}の今日のBoatStrikers`}><img src="/today/8EB455BA-4012-4C9A-9E1C-793E5F59B7FF.png" alt="今日のBoatStrikers" className={styles.heroBanner} fetchPriority="high"/><div className={styles.heroBadges}><span>📅 <b>{formatDate(displayDate)}</b></span><span>🚤 開催 <b>{courses.length}場</b></span><span>🏁 <b>{finishedRaces}/{totalRaces}R</b></span>{grades.length?<span>🏆 グレード戦 <b>{grades.length}件</b></span>:null}</div></section>

  <section className={`${styles.dailySummary} ${visualStyles.panel}`}><div><small>BOATSTRIKERS DAILY</small><h1>今日のボートレースを、ここから。</h1><p>開催状況、3人のコンテンツ、グレード戦、誕生日レーサーまで今日必要な情報をまとめました。</p></div><div className={styles.summaryStats}><div><b>{courses.length}</b><span>開催場</span></div><div><b>{totalRaces}</b><span>レース</span></div><div><b>{liveCourses}</b><span>進行中</span></div><div><b>{todayPapers.length}</b><span>新聞</span></div></div></section>

  <section className={`${styles.section} ${visualStyles.panel}`}><div className={styles.sectionTitle}><div><small>TODAY'S 3 STRIKERS</small><h2>今日の3人</h2></div><Link href="/library">記事一覧 ›</Link></div><div className={styles.strikerGrid}>{CHARACTERS.map(ch=>{const paper=paperByCharacter.get(ch.key);return <article className={`${styles.strikerCard} ${styles[ch.tone]}`} key={ch.key}><div className={styles.strikerTop}><span>{ch.emoji}</span><div><small>{ch.role}</small><strong>{ch.name}</strong></div></div><p>{paper?`${paper.course_name}${paper.race_no}R・${paper.edition==="just_before"?"直前版":"前日版"}を公開中`:ch.copy}</p><div className={styles.strikerActions}>{paper?<Link href={`/newspapers/${paper.slug}`}>今日の新聞を読む</Link>:<span>本日の新聞は準備中</span>}<Link href={ch.href}>{ch.name}の部屋 ›</Link></div></article>})}</div></section>

  <section className={`${styles.section} ${visualStyles.panel}`}><div className={styles.sectionTitle}><div><small>RACE CENTER</small><h2>今日の開催場</h2></div><Link href={`/races?date=${displayDate}`}>全レースを見る ›</Link></div>{courses.length?<div className={styles.courseGrid}>{courses.map(c=><Link href={`/races/${c.courseCode}?date=${displayDate}`} className={styles.courseCard} key={c.courseCode}><div className={styles.courseHead}><strong>{c.courseName||COURSE_NAMES[c.courseCode]}</strong><span className={`${styles.status} ${styles[c.liveStatus]||""}`}>{c.liveStatus==="finished"?"終了":c.liveStatus==="live"?"LIVE":c.liveStatus==="exhibition"?"展示中":"開催中"}</span></div><div className={styles.courseProgress}><span style={{width:`${c.raceCount?Math.min(100,(c.resultCount/c.raceCount)*100):0}%`}}/></div><div className={styles.courseMeta}><span>{c.resultCount}/{c.raceCount}R 終了</span>{c.nextRaceNo?<b>次 {c.nextRaceNo}R {c.nextClosingTime||""}</b>:<b>結果を見る</b>}</div></Link>)}</div>:<p className={styles.empty}>開催情報を取得しています。</p>}</section>

  <section className={`${styles.topicSection} ${visualStyles.panel}`}><h2 className={styles.bannerHeading}><img src="/today/D83A0221-B4E5-4F4E-876B-7512587225B9.png" alt="今日のトピックス" className={styles.sectionBanner}/></h2><div className={styles.topicGrid}>{birthdayRacers.length?<a href="#birthdays" className={`${styles.topicCard} ${styles.birthdayTopic}`}><span>🎂</span><div><small>HAPPY BIRTHDAY</small><strong>誕生日レーサー {birthdayRacers.length}人</strong><p>{birthdayRacers.map(x=>x.name).join("・")}</p></div><b>↓</b></a>:null}{grades.slice(0,2).map((g,i)=><Link className={styles.topicCard} key={`${g.course_code}-${i}`} href={`/races/${Number(g.course_code)}?date=${displayDate}`}><span>🏆</span><div><small>{String(g.grade).toUpperCase()} / {COURSE_NAMES[Number(g.course_code)]}</small><strong>{g.title||"グレードレース開催中"}</strong><p>本日の開催情報を見る</p></div><b>›</b></Link>)}<Link className={`${styles.topicCard} ${styles.raceTopic}`} href={`/races?date=${displayDate}`}><span>🚤</span><div><small>RACE CENTER</small><strong>今日のレース情報</strong><p>出走表・展示・分析をまとめて確認</p></div><b>›</b></Link></div></section>

  <section className={`${styles.section} ${styles.bannerPanel} ${visualStyles.panel}`}><h2 className={`${styles.bannerHeading} ${styles.todayContentHeading}`}><img src="/today/FC3BEB6E-E4B1-447B-B3F5-C04E3B6B2E55.png" alt="今日のBoatStrikers" className={styles.sectionBanner}/></h2><div className={styles.paperGrid}>{todayPapers.length?todayPapers.map(item=>{const ch=CHARACTERS.find(x=>x.key===item.character_key)||CHARACTERS[0];return <Link href={`/newspapers/${item.slug}`} className={`${styles.paper} ${styles[ch.tone]}`} key={item.id}><span>{ch.emoji}</span><div><small>{ch.name}・{item.edition==="just_before"?"直前版":"前日版"}</small><strong>{item.course_name}{item.race_no}R</strong><p>{item.title}</p></div><b>読む ›</b></Link>}):CHARACTERS.map(ch=><Link href={ch.href} className={`${styles.paper} ${styles[ch.tone]}`} key={ch.key}><span>{ch.emoji}</span><div><small>{ch.role}</small><strong>{ch.name}の新聞</strong><p>本日の新聞は準備中です</p></div><b>見る ›</b></Link>)}</div><div className={styles.mediaGrid}><Link href="/data-lab"><span>📊</span><div><small>DATA LAB</small><strong>昨日を数字で振り返る</strong></div><b>›</b></Link><Link href="/news"><span>📰</span><div><small>NEWS</small><strong>今日のニュースを読む</strong></div><b>›</b></Link><Link href="/schedule"><span>🎙️</span><div><small>SCHEDULE</small><strong>配信予定を見る</strong></div><b>›</b></Link></div></section>

  {grades.length?<section className={`${styles.section} ${styles.bannerPanel} ${visualStyles.panel}`}><h2 className={styles.bannerHeading}><img src="/today/B36F7AF4-D8EC-477D-B925-E58308AC100D.png" alt="今日のグレード戦" className={`${styles.sectionBanner} ${styles.gradeBanner}`}/></h2><div className={styles.gradeGrid}>{grades.map((g,i)=><Link className={styles.grade} key={`${g.course_code}-${i}`} href={`/races/${Number(g.course_code)}?date=${displayDate}`}><span>{String(g.grade).toUpperCase()}</span><div><strong>{g.title||"グレードレース"}</strong><small>{COURSE_NAMES[Number(g.course_code)]}</small></div><b>開催情報 ›</b></Link>)}</div></section>:null}

  {birthdayRacers.length?<section className={`${styles.section} ${styles.bannerPanel} ${visualStyles.panel}`} id="birthdays"><h2 className={styles.bannerHeading}><img src="/today/07588D39-D6E8-45A9-8DAE-08D1CF90BF2D.png" alt="今日の誕生日レーサー" className={styles.sectionBanner}/></h2><div className={styles.birthdayGrid}>{birthdayRacers.map(r=><article className={styles.birthdayCard} key={r.registration_no}><div className={styles.birthdayHead}><span>🎂</span><div><strong>{r.name}</strong><small>登録 {Number(r.registration_no)} / {r.branch||"-"} / {r.racer_class||"-"}</small></div><b>{Number(r.birthday?.slice(5,7))}/{Number(r.birthday?.slice(8,10))}</b></div><div className={styles.birthdayRaces}>{r.races.map((race,i)=><Link key={`${race.course_code}-${race.race_no}-${i}`} href={raceHref(race.course_code,race.race_no,displayDate)}><span>{COURSE_NAMES[Number(race.course_code)]} {Number(race.race_no)}R</span><small>{Number(race.boat_no)}号艇</small><b>出走表 →</b></Link>)}</div></article>)}</div></section>:null}

  <Link className={styles.raceCtaBannerLink} href={`/races?date=${displayDate}`} aria-label="レースを探す・見る"><img src="/today/0F703DB2-FB5E-4BF0-B003-1F6952D1E955.png" alt="レースを探す・見る" className={styles.raceCtaBanner}/></Link>
  {!member.authenticated?<Link className={styles.memberSignupBannerLink} href="/members" aria-label="無料会員登録"><img src="/beta-membership-banner.webp" alt="BoatStrikers 無料会員登録" className={styles.memberSignupBanner}/></Link>:null}
 </main>;
}