"use client";
import { useEffect, useMemo, useState } from "react";
import styles from "./realtimeAdmin.module.css";

const initial={kind:"prediction",character:"all",title:"",body:"",link_url:"",image_url:"",published_at:"",is_active:true,show_home:true,show_races:true,show_ichika:false,show_hatsune:false,show_kiina:false};
const kindLabels={prediction:"🎯 予想",hit:"🎉 的中",update:"📰 更新",radio:"🎙️ ラジオ",video:"▶️ 動画",notice:"📢 お知らせ"};
const characterLabels={all:"BoatStrikers",ichika:"一果",hatsune:"初音",kiina:"キイナ"};

function localDateTime(date=new Date()){const f=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false});return f.format(date).replace(" ","T")}
export default function RealtimeAdminClient(){
 const [form,setForm]=useState({...initial,published_at:localDateTime()}); const [items,setItems]=useState([]); const [editId,setEditId]=useState(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/realtime/items",{cache:"no-store"});const j=await r.json();if(r.ok)setItems(j.items||[]);else setMessage(j.error||"取得失敗");}
 useEffect(()=>{load()},[]);
 function field(key,value){setForm(v=>({...v,[key]:value}))}
 function chooseCharacter(value){setForm(v=>({...v,character:value,show_ichika:value==="ichika"||value==="all",show_hatsune:value==="hatsune"||value==="all",show_kiina:value==="kiina"||value==="all"}))}
 async function upload(file){if(!file)return;setBusy(true);setMessage("画像をアップロード中…");const data=new FormData();data.append("file",file);const r=await fetch("/api/admin/realtime/upload",{method:"POST",body:data});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.error||"画像アップロード失敗");return}field("image_url",j.url);setMessage("画像をアップロードしました");}
 async function save(e){e.preventDefault();setBusy(true);setMessage("");const url=editId?`/api/admin/realtime/items/${editId}`:"/api/admin/realtime/items";const r=await fetch(url,{method:editId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.error||"保存失敗");return}setMessage("保存しました");setEditId(null);setForm({...initial,published_at:localDateTime()});await load();}
 function edit(item){setEditId(item.id);setForm({...initial,...item,published_at:item.published_at?localDateTime(new Date(item.published_at)):localDateTime()});window.scrollTo({top:0,behavior:"smooth"})}
 async function remove(id){if(!confirm("削除しますか？"))return;await fetch(`/api/admin/realtime/items/${id}`,{method:"DELETE"});await load()}
 const xText=useMemo(()=>{const icon={prediction:"🎯",hit:"🎉",update:"📰",radio:"🎙️",video:"▶️",notice:"📢"}[form.kind]||"📢";const who=characterLabels[form.character]||"BoatStrikers";return `${icon} ${form.title||"BoatStrikers更新情報"}\n${who}${form.body?`\n${form.body}`:""}${form.link_url?`\n${form.link_url}`:""}\n#BoatStrikers #ボートレース`},[form]);
 function openX(){window.open(`https://x.com/intent/post?text=${encodeURIComponent(xText)}`,"_blank","noopener,noreferrer")}
 async function copyX(){await navigator.clipboard.writeText(xText);setMessage("X投稿文をコピーしました")}
 return <main className={styles.page}><header><span>BOATSTRIKERS CMS</span><h1>リアルタイム更新管理</h1><p>1回の登録でトップ・出走表・各キャラページへ反映できます。</p></header>
 <form className={styles.panel} onSubmit={save}><div className={styles.grid3}><label>種類<select value={form.kind} onChange={e=>field("kind",e.target.value)}>{Object.entries(kindLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>担当<select value={form.character} onChange={e=>chooseCharacter(e.target.value)}>{Object.entries(characterLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>公開日時<input type="datetime-local" value={form.published_at||""} onChange={e=>field("published_at",e.target.value)}/></label></div>
 <label>タイトル<input required value={form.title} onChange={e=>field("title",e.target.value)} placeholder="例：桐生8R イン逃げ注目"/></label><label>本文<textarea rows="4" value={form.body||""} onChange={e=>field("body",e.target.value)} placeholder="短い速報コメント"/></label><label>リンク先<input value={form.link_url||""} onChange={e=>field("link_url",e.target.value)} placeholder="/races/01/8 または https://..."/></label>
 <div className={styles.imageBox}><div className={styles.preview}>{form.image_url?<img src={form.image_url} alt="プレビュー"/>:<span>テレボート等のスクショを添付できます</span>}</div><label className={styles.upload}>画像を選択<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><input value={form.image_url||""} onChange={e=>field("image_url",e.target.value)} placeholder="画像URL（任意）"/></div>
 <p className={styles.caution}>※ 公開前に会員番号・残高・氏名・購入履歴など個人情報が写っていないか確認してください。</p>
 <div className={styles.checks}><label><input type="checkbox" checked={form.is_active} onChange={e=>field("is_active",e.target.checked)}/>公開</label><label><input type="checkbox" checked={form.show_home} onChange={e=>field("show_home",e.target.checked)}/>トップ</label><label><input type="checkbox" checked={form.show_races} onChange={e=>field("show_races",e.target.checked)}/>出走表</label><label><input type="checkbox" checked={form.show_ichika} onChange={e=>field("show_ichika",e.target.checked)}/>一果</label><label><input type="checkbox" checked={form.show_hatsune} onChange={e=>field("show_hatsune",e.target.checked)}/>初音</label><label><input type="checkbox" checked={form.show_kiina} onChange={e=>field("show_kiina",e.target.checked)}/>キイナ</label></div>
 <div className={styles.actions}><button type="submit" disabled={busy}>{editId?"更新する":"サイトに公開"}</button>{editId?<button type="button" className={styles.secondary} onClick={()=>{setEditId(null);setForm({...initial,published_at:localDateTime()})}}>編集をやめる</button>:null}</div></form>
 <section className={styles.xPanel}><h2>𝕏 投稿用</h2><pre>{xText}</pre><div className={styles.actions}><button type="button" onClick={copyX}>投稿文をコピー</button><button type="button" onClick={openX}>Xで投稿する ↗</button></div><small>「Xで投稿する」はXの投稿画面を開きます。サイトへの登録とは別操作です。</small></section>{message?<p className={styles.message}>{message}</p>:null}
 <section className={styles.list}><h2>登録済み</h2>{items.map(item=><article key={item.id}><div><strong>{kindLabels[item.kind]}　{item.title}</strong><small>{characterLabels[item.character]} / {item.published_at?new Date(item.published_at).toLocaleString("ja-JP"):""}</small></div><div><button onClick={()=>edit(item)}>編集</button><button className={styles.delete} onClick={()=>remove(item.id)}>削除</button></div></article>)}</section></main>
}
