create table if not exists public.hatsune_news (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  category text not null default 'topic',
  source_type text not null default 'news',
  source_name text,
  source_url text,
  image_url text,
  place text,
  published_at timestamptz not null default now(),
  is_featured boolean not null default false,
  priority integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hatsune_news_category_check check (
    category in ('result','women','suijinsai','win','grade','motor','tomorrow','topic')
  ),
  constraint hatsune_news_source_type_check check (
    source_type in ('news','official','bs_data')
  )
);

create index if not exists hatsune_news_public_feed_idx
  on public.hatsune_news (is_published, is_featured desc, priority desc, published_at desc);

create index if not exists hatsune_news_category_idx
  on public.hatsune_news (category, published_at desc);

alter table public.hatsune_news enable row level security;

-- 公開済みNEWSは匿名ユーザーから読み取り可能。
drop policy if exists "public can read published hatsune news" on public.hatsune_news;
create policy "public can read published hatsune news"
  on public.hatsune_news
  for select
  to anon, authenticated
  using (is_published = true);

comment on table public.hatsune_news is '初音 女子ボートNEWS。夜間収集・BS DATA・公式ニュースを共通形式で保存する。';
comment on column public.hatsune_news.source_type is 'news=報道、official=公式、bs_data=BoatStrikers独自データ';
