-- Daily DATA LAB metrics for improving Ichika's 1-head prediction strategy.
-- This table is additive only and does not modify historical predictions/results.

create table if not exists public.bs_ichika_ai_analysis_metrics (
  id bigint generated by default as identity primary key,
  analysis_date date not null,
  window_days integer not null default 30 check (window_days between 1 and 365),
  period_start date not null,
  period_end date not null,
  timing text not null check (timing in ('previous_day', 'after_exhibition')),
  metric text not null,
  bucket text not null,
  races integer not null default 0,
  tickets integer not null default 0,
  hits integer not null default 0,
  hit_rate numeric(8,2),
  recovery_rate numeric(10,2),
  avg_tickets numeric(8,2),
  sample_sufficient boolean not null default false,
  generated_at timestamptz not null default now(),
  unique (analysis_date, window_days, timing, metric, bucket)
);

create index if not exists idx_ichika_ai_analysis_date
  on public.bs_ichika_ai_analysis_metrics (analysis_date desc);

create index if not exists idx_ichika_ai_analysis_metric
  on public.bs_ichika_ai_analysis_metrics (metric, timing, analysis_date desc);

alter table public.bs_ichika_ai_analysis_metrics enable row level security;

revoke all on table public.bs_ichika_ai_analysis_metrics from anon, authenticated;
grant all on table public.bs_ichika_ai_analysis_metrics to service_role;

create or replace function public.refresh_ichika_ai_analysis(
  p_target_date date default (timezone('Asia/Tokyo', now()))::date,
  p_window_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_start date;
  v_inserted integer := 0;
begin
  if p_target_date is null then
    raise exception 'p_target_date is required';
  end if;

  if p_window_days is null or p_window_days < 1 or p_window_days > 365 then
    raise exception 'p_window_days must be between 1 and 365';
  end if;

  v_start := p_target_date - (p_window_days - 1);

  delete from public.bs_ichika_ai_analysis_metrics
  where analysis_date = p_target_date
    and window_days = p_window_days;

  with official_dedup as (
    select distinct on (p.race_date, p.course_code, p.race_no, p.timing)
      p.id,
      p.race_date,
      p.course_code,
      p.race_no,
      p.timing,
      p.tickets,
      p.published_at
    from public.bsc_official_predictions p
    where p.character_code = 'ichika'
      and p.source_table = 'bs_ai_predictions'
      and p.race_date between v_start and p_target_date
      and p.timing in ('previous_day', 'after_exhibition')
    order by
      p.race_date,
      p.course_code,
      p.race_no,
      p.timing,
      p.published_at asc,
      p.id asc
  ),
  base as (
    select
      p.race_date,
      p.course_code,
      p.race_no,
      p.timing,
      p.tickets,
      r.result_combination,
      r.trifecta_payout,
      e.wind_speed,
      lane1.national_win_rate,
      lane1.local_win_rate,
      coalesce(lane1.motor_top2_rate, lane1.motor_2_rate) as motor_2_rate,
      lane1.average_st,
      coalesce(lane1.course1_top2_rate, lane1.course1_2_rate) as course1_top2_rate,
      lane1.exhibition_time_rank,
      lane1.start_exhibition_rank
    from official_dedup p
    join public.bsc_official_results r
      on r.prediction_id = p.id
    left join public.bs_race_events e
      on e.race_date = p.race_date
     and e.course_code = p.course_code
     and e.race_no = p.race_no
    left join public.bs_race_entries lane1
      on lane1.race_date = p.race_date
     and lane1.course_code = p.course_code
     and lane1.race_no = p.race_no
     and lane1.boat_no = 1
  ),
  simulated as (
    select
      b.*,
      (
        select count(*)::integer
        from jsonb_array_elements_text(coalesce(b.tickets, '[]'::jsonb)) x(ticket)
        where split_part(x.ticket, '-', 1) = '1'
      ) as ticket_count,
      exists (
        select 1
        from jsonb_array_elements_text(coalesce(b.tickets, '[]'::jsonb)) x(ticket)
        where split_part(x.ticket, '-', 1) = '1'
          and x.ticket = b.result_combination
      ) as hit
    from base b
  ),
  eligible as (
    select *
    from simulated
    where ticket_count > 0
  ),
  expanded as (
    select *, 'overall'::text as metric, 'all'::text as bucket
    from eligible

    union all
    select *, 'national_win_rate',
      case
        when national_win_rate is null then 'NA'
        when national_win_rate < 5 then '<5.0'
        when national_win_rate < 6 then '5.0-5.99'
        when national_win_rate < 7 then '6.0-6.99'
        else '7.0+'
      end
    from eligible

    union all
    select *, 'local_win_rate',
      case
        when local_win_rate is null then 'NA'
        when local_win_rate < 5 then '<5.0'
        when local_win_rate < 6 then '5.0-5.99'
        when local_win_rate < 7 then '6.0-6.99'
        else '7.0+'
      end
    from eligible

    union all
    select *, 'motor_2_rate',
      case
        when motor_2_rate is null then 'NA'
        when motor_2_rate < 30 then '<30%'
        when motor_2_rate < 40 then '30-39.9%'
        when motor_2_rate < 50 then '40-49.9%'
        else '50%+'
      end
    from eligible

    union all
    select *, 'average_st',
      case
        when average_st is null then 'NA'
        when average_st <= 0.13 then '<=0.13'
        when average_st <= 0.16 then '0.14-0.16'
        when average_st <= 0.19 then '0.17-0.19'
        else '0.20+'
      end
    from eligible

    union all
    select *, 'course1_top2_rate',
      case
        when course1_top2_rate is null then 'NA'
        when course1_top2_rate < 60 then '<60%'
        when course1_top2_rate < 70 then '60-69.9%'
        when course1_top2_rate < 80 then '70-79.9%'
        else '80%+'
      end
    from eligible

    union all
    select *, 'course',
      lpad(course_code::text, 2, '0')
    from eligible

    union all
    select *, 'wind',
      case
        when wind_speed is null then 'NA'
        when wind_speed < 2 then '<2m'
        when wind_speed < 4 then '2-3.9m'
        when wind_speed < 6 then '4-5.9m'
        else '6m+'
      end
    from eligible
    where timing = 'after_exhibition'

    union all
    select *, 'exhibition_time_rank',
      case
        when exhibition_time_rank is null then 'NA'
        when exhibition_time_rank = 1 then '1位'
        when exhibition_time_rank <= 3 then '2-3位'
        else '4-6位'
      end
    from eligible
    where timing = 'after_exhibition'

    union all
    select *, 'start_exhibition_rank',
      case
        when start_exhibition_rank is null then 'NA'
        when start_exhibition_rank = 1 then '1位'
        when start_exhibition_rank <= 3 then '2-3位'
        else '4-6位'
      end
    from eligible
    where timing = 'after_exhibition'
  ),
  aggregated as (
    select
      timing,
      metric,
      bucket,
      count(*)::integer as races,
      sum(ticket_count)::integer as tickets,
      count(*) filter (where hit)::integer as hits,
      round(
        100.0 * count(*) filter (where hit) / nullif(count(*), 0),
        2
      ) as hit_rate,
      round(
        100.0 * sum(case when hit then coalesce(trifecta_payout, 0) else 0 end)
        / nullif(sum(ticket_count * 100), 0),
        2
      ) as recovery_rate,
      round(avg(ticket_count)::numeric, 2) as avg_tickets
    from expanded
    group by timing, metric, bucket
  )
  insert into public.bs_ichika_ai_analysis_metrics (
    analysis_date,
    window_days,
    period_start,
    period_end,
    timing,
    metric,
    bucket,
    races,
    tickets,
    hits,
    hit_rate,
    recovery_rate,
    avg_tickets,
    sample_sufficient,
    generated_at
  )
  select
    p_target_date,
    p_window_days,
    v_start,
    p_target_date,
    timing,
    metric,
    bucket,
    races,
    tickets,
    hits,
    hit_rate,
    recovery_rate,
    avg_tickets,
    races >= 100,
    clock_timestamp()
  from aggregated;

  get diagnostics v_inserted = row_count;

  return jsonb_build_object(
    'ok', true,
    'analysis_date', p_target_date,
    'window_days', p_window_days,
    'period_start', v_start,
    'period_end', p_target_date,
    'metrics_written', v_inserted
  );
end;
$function$;

revoke all on function public.refresh_ichika_ai_analysis(date, integer) from public, anon, authenticated;
grant execute on function public.refresh_ichika_ai_analysis(date, integer) to service_role;
