create table if not exists public.bs_hatsune_womens_inner_break_alerts (
  id bigint generated by default as identity primary key,
  race_date date not null,
  course_code smallint not null,
  course_name text,
  race_no smallint not null,
  closing_time time,
  boat1_exhibition numeric,
  boat2_exhibition numeric,
  exhibition_advantage numeric,
  boat1_lap numeric,
  boat2_lap numeric,
  lap_advantage numeric,
  danger_level text not null default 'danger',
  detected_at timestamptz not null default now(),
  notified boolean not null default false,
  notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (race_date, course_code, race_no)
);

create index if not exists bs_hatsune_womens_inner_break_pending_idx
  on public.bs_hatsune_womens_inner_break_alerts (race_date, notified, detected_at);

create or replace function public.evaluate_hatsune_womens_inner_break_alerts()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare inserted_count integer := 0;
begin
  with women_races as (
    select race_date, course_code, race_no
    from public.bs_race_entries
    where race_date = (now() at time zone 'Asia/Tokyo')::date
    group by race_date, course_code, race_no
    having count(*) filter (where gender_code = '2') = 6 and count(*) = 6
  ), paired as (
    select e1.race_date,e1.course_code,ev.course_name,e1.race_no,ev.closing_time,
      e1.official_exhibition_time boat1_exhibition,e2.official_exhibition_time boat2_exhibition,
      (e1.official_exhibition_time-e2.official_exhibition_time) exhibition_advantage,
      e1.official_lap boat1_lap,e2.official_lap boat2_lap,(e1.official_lap-e2.official_lap) lap_advantage,
      case when e3.official_exhibition_time is not null and e3.official_lap is not null
        and (e1.official_exhibition_time-e3.official_exhibition_time)>=0.05
        and (e1.official_lap-e3.official_lap)>=0.10 then 'super_danger' else 'danger' end danger_level
    from women_races w
    join public.bs_race_entries e1 on e1.race_date=w.race_date and e1.course_code=w.course_code and e1.race_no=w.race_no and e1.boat_no=1
    join public.bs_race_entries e2 on e2.race_date=w.race_date and e2.course_code=w.course_code and e2.race_no=w.race_no and e2.boat_no=2
    left join public.bs_race_entries e3 on e3.race_date=w.race_date and e3.course_code=w.course_code and e3.race_no=w.race_no and e3.boat_no=3
    join public.bs_race_events ev on ev.race_date=w.race_date and ev.course_code=w.course_code and ev.race_no=w.race_no
    where e1.official_exhibition_time is not null and e2.official_exhibition_time is not null
      and e1.official_lap is not null and e2.official_lap is not null
      and (e1.official_exhibition_time-e2.official_exhibition_time)>=0.05
      and (e1.official_lap-e2.official_lap)>=0.10
      and (ev.race_date+ev.closing_time) at time zone 'Asia/Tokyo' > now()
      and (ev.race_date+ev.closing_time) at time zone 'Asia/Tokyo' <= now()+interval '30 minutes'
  )
  insert into public.bs_hatsune_womens_inner_break_alerts (
    race_date,course_code,course_name,race_no,closing_time,boat1_exhibition,boat2_exhibition,
    exhibition_advantage,boat1_lap,boat2_lap,lap_advantage,danger_level
  ) select race_date,course_code,course_name,race_no,closing_time,boat1_exhibition,boat2_exhibition,
    exhibition_advantage,boat1_lap,boat2_lap,lap_advantage,danger_level from paired
  on conflict (race_date,course_code,race_no) do nothing;
  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;
