create table if not exists public.hatsune_news_videos (
  id bigint generated by default as identity primary key,
  video_type text not null,
  target_date date,
  period_start date,
  period_end date,
  source_article_ids bigint[] not null default '{}',
  title text not null default '',
  script text not null default '',
  caption_json jsonb not null default '[]'::jsonb,
  youtube_title text,
  youtube_description text,
  x_text text,
  hashtags text[] not null default '{}',
  status text not null default 'draft',
  duration_seconds integer,
  ai_model text,
  ai_generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hatsune_news_videos_type_check check (video_type in ('daily_short','weekly_news')),
  constraint hatsune_news_videos_status_check check (status in ('draft','approved','rendered','published')),
  constraint hatsune_news_videos_period_check check (
    (video_type = 'daily_short' and target_date is not null)
    or
    (video_type = 'weekly_news' and period_start is not null and period_end is not null)
  )
);

create index if not exists hatsune_news_videos_created_idx
  on public.hatsune_news_videos (created_at desc);

create index if not exists hatsune_news_videos_target_idx
  on public.hatsune_news_videos (video_type, target_date desc, period_start desc);

alter table public.hatsune_news_videos enable row level security;

comment on table public.hatsune_news_videos is '初音の今日のヴィーナスNEWS／週間ヴィーナスNEWSのAI台本と投稿素材を保存する。';
comment on column public.hatsune_news_videos.caption_json is '動画字幕。[{text,start,end}]を想定し、初期段階ではtextのみでも可。';
