-- Daily AI improvement metrics for Hatsune (women's races) and Kiina (5-head).
-- Uses only officially frozen published ranking predictions and never rewrites historical predictions/results.

create table if not exists public.bs_character_ai_analysis_metrics (
  id bigint generated by default as identity primary key,
  analysis_date date not null,
  window_days integer not null default 30 check (window_days between 1 and 365),
  period_start date not null,
  period_end date not null,
  character_code text not null check (character_code in ('hatsune','kiina')),
  timing text not null default 'previous_day',
  metric text not null,
  bucket text not null,
  races integer not null default 0,
  tickets integer not null default 0,
  hits integer not null default 0,
  hit_rate numeric(8,2),
  recovery_rate numeric(10,2),
  avg_tickets numeric(8,2),
  sample_sufficient boolean not null default false,
  generated_at timestamptz not null default now(),
  unique (analysis_date, window_days, character_code, timing, metric, bucket)
);

create index if not exists idx_character_ai_analysis_date
  on public.bs_character_ai_analysis_metrics (character_code, analysis_date desc);

create index if not exists idx_character_ai_analysis_metric
  on public.bs_character_ai_analysis_metrics (character_code, metric, analysis_date desc);

alter table public.bs_character_ai_analysis_metrics enable row level security;
revoke all on table public.bs_character_ai_analysis_metrics from anon, authenticated;
grant all on table public.bs_character_ai_analysis_metrics to service_role;

create or replace function public.refresh_hatsune_kiina_ai_analysis(
  p_target_date date default (timezone('Asia/Tokyo', now()))::date,
  p_window_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_start date;
  v_inserted integer := 0;
begin
  if p_target_date is null then
    raise exception 'p_target_date is required';
  end if;

  if p_window_days is null or p_window_days < 1 or p_window_days > 365 then
    raise exception 'p_window_days must be between 1 and 365';
  end if;

  v_start := p_target_date - (p_window_days - 1);

  delete from public.bs_character_ai_analysis_metrics
  where analysis_date = p_target_date
    and window_days = p_window_days
    and character_code in ('hatsune','kiina');

  with official_dedup as (
    select distinct on (p.character_code, p.race_date, p.course_code, p.race_no, p.timing)
      p.id,
      p.character_code,
      p.race_date,
      p.course_code,
      p.race_no,
      p.timing,
      p.tickets,
      p.investment,
      p.source_id,
      p.published_at
    from public.bsc_official_predictions p
    where p.character_code in ('hatsune','kiina')
      and p.source_table = 'ai_v2_daily_rankings_published'
      and p.race_date between v_start and p_target_date
      and p.timing = 'previous_day'
    order by
      p.character_code,
      p.race_date,
      p.course_code,
      p.race_no,
      p.timing,
      p.published_at asc,
      p.id asc
  ),
  base as (
    select
      p.character_code,
      p.race_date,
      p.course_code,
      p.race_no,
      p.timing,
      p.tickets,
      p.investment,
      r.result_combination,
      r.trifecta_payout,
      r.is_hit,
      r.payout,
      rank.rank_no,
      rank.probability,
      rank.metrics,
      lane1.national_win_rate as lane1_national_win_rate,
      lane1.local_win_rate as lane1_local_win_rate,
      coalesce(lane1.motor_top2_rate, lane1.motor_2_rate) as lane1_motor_2_rate,
      lane1.average_st as lane1_average_st,
      boat5.national_win_rate as boat5_national_win_rate,
      boat5.local_win_rate as boat5_local_win_rate,
      coalesce(boat5.motor_top2_rate, boat5.motor_2_rate) as boat5_motor_2_rate,
      boat5.average_st as boat5_average_st
    from official_dedup p
    join public.bsc_official_results r
      on r.prediction_id = p.id
    left join public.ai_v2_daily_rankings rank
      on rank.id::text = p.source_id
    left join public.bs_race_entries lane1
      on lane1.race_date = p.race_date
     and lane1.course_code = p.course_code
     and lane1.race_no = p.race_no
     and lane1.boat_no = 1
    left join public.bs_race_entries boat5
      on boat5.race_date = p.race_date
     and boat5.course_code = p.course_code
     and boat5.race_no = p.race_no
     and boat5.boat_no = 5
  ),
  normalized as (
    select
      b.*,
      coalesce(jsonb_array_length(b.tickets),0)::integer as ticket_count,
      case
        when b.character_code = 'kiina' then
          exists (
            select 1
            from jsonb_array_elements_text(coalesce(b.tickets,'[]'::jsonb)) x(ticket)
            where split_part(x.ticket,'-',1) = '5'
              and x.ticket = b.result_combination
          )
        else coalesce(b.is_hit,false)
      end as specialist_hit,
      case
        when b.character_code = 'kiina' then
          (select count(*)::integer
           from jsonb_array_elements_text(coalesce(b.tickets,'[]'::jsonb)) x(ticket)
           where split_part(x.ticket,'-',1) = '5')
        else coalesce(jsonb_array_length(b.tickets),0)::integer
      end as specialist_ticket_count
    from base b
  ),
  eligible as (
    select *
    from normalized
    where specialist_ticket_count > 0
  ),
  expanded as (
    select *, 'overall'::text as metric, 'all'::text as bucket
    from eligible

    union all
    select *, 'ranking_probability',
      case
        when probability is null then 'NA'
        when character_code='hatsune' and probability < 0.60 then '<0.60'
        when character_code='hatsune' and probability < 0.70 then '0.60-0.69'
        when character_code='hatsune' and probability < 0.80 then '0.70-0.79'
        when character_code='hatsune' then '0.80+'
        when character_code='kiina' and probability < 0.14 then '<0.14'
        when character_code='kiina' and probability < 0.15 then '0.14-0.149'
        when character_code='kiina' and probability < 0.16 then '0.15-0.159'
        else '0.16+'
      end
    from eligible

    union all
    select *, 'rank_no',
      case
        when rank_no is null then 'NA'
        when rank_no=1 then '1位'
        when rank_no<=3 then '2-3位'
        else '4-5位'
      end
    from eligible

    union all
    select *, 'course', lpad(course_code::text,2,'0')
    from eligible

    union all
    select *, 'lane1_national_win_rate',
      case
        when lane1_national_win_rate is null then 'NA'
        when lane1_national_win_rate < 5 then '<5.0'
        when lane1_national_win_rate < 6 then '5.0-5.99'
        when lane1_national_win_rate < 7 then '6.0-6.99'
        else '7.0+'
      end
    from eligible

    union all
    select *, 'lane1_motor_2_rate',
      case
        when lane1_motor_2_rate is null then 'NA'
        when lane1_motor_2_rate < 30 then '<30%'
        when lane1_motor_2_rate < 40 then '30-39.9%'
        when lane1_motor_2_rate < 50 then '40-49.9%'
        else '50%+'
      end
    from eligible

    union all
    select *, 'boat5_national_win_rate',
      case
        when boat5_national_win_rate is null then 'NA'
        when boat5_national_win_rate < 4 then '<4.0'
        when boat5_national_win_rate < 5 then '4.0-4.99'
        when boat5_national_win_rate < 6 then '5.0-5.99'
        else '6.0+'
      end
    from eligible
    where character_code='kiina'

    union all
    select *, 'boat5_motor_2_rate',
      case
        when boat5_motor_2_rate is null then 'NA'
        when boat5_motor_2_rate < 30 then '<30%'
        when boat5_motor_2_rate < 40 then '30-39.9%'
        when boat5_motor_2_rate < 50 then '40-49.9%'
        else '50%+'
      end
    from eligible
    where character_code='kiina'

    union all
    select *, 'boat5_average_st',
      case
        when boat5_average_st is null then 'NA'
        when boat5_average_st <= 0.13 then '<=0.13'
        when boat5_average_st <= 0.16 then '0.14-0.16'
        when boat5_average_st <= 0.19 then '0.17-0.19'
        else '0.20+'
      end
    from eligible
    where character_code='kiina'
  ),
  aggregated as (
    select
      character_code,
      timing,
      metric,
      bucket,
      count(*)::integer as races,
      sum(specialist_ticket_count)::integer as tickets,
      count(*) filter(where specialist_hit)::integer as hits,
      round(100.0 * count(*) filter(where specialist_hit) / nullif(count(*),0),2) as hit_rate,
      round(
        100.0 * sum(case when specialist_hit then coalesce(trifecta_payout,0) else 0 end)
        / nullif(sum(specialist_ticket_count * 100),0),
        2
      ) as recovery_rate,
      round(avg(specialist_ticket_count)::numeric,2) as avg_tickets
    from expanded
    group by character_code,timing,metric,bucket
  )
  insert into public.bs_character_ai_analysis_metrics (
    analysis_date,window_days,period_start,period_end,character_code,timing,
    metric,bucket,races,tickets,hits,hit_rate,recovery_rate,avg_tickets,
    sample_sufficient,generated_at
  )
  select
    p_target_date,p_window_days,v_start,p_target_date,character_code,timing,
    metric,bucket,races,tickets,hits,hit_rate,recovery_rate,avg_tickets,
    races >= 100,clock_timestamp()
  from aggregated;

  get diagnostics v_inserted = row_count;

  return jsonb_build_object(
    'ok', true,
    'analysis_date', p_target_date,
    'window_days', p_window_days,
    'period_start', v_start,
    'period_end', p_target_date,
    'metrics_written', v_inserted
  );
end;
$function$;

revoke all on function public.refresh_hatsune_kiina_ai_analysis(date, integer) from public, anon, authenticated;
grant execute on function public.refresh_hatsune_kiina_ai_analysis(date, integer) to service_role;
