create table if not exists public.hatsune_news_cron_runs (
  id bigint generated by default as identity primary key,
  job_name text not null check (job_name in ('pipeline','ai')),
  status text not null check (status in ('running','success','error','partial')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer,
  collected_count integer not null default 0,
  inserted_count integer not null default 0,
  skipped_count integer not null default 0,
  ai_processed_count integer not null default 0,
  ai_generated_count integer not null default 0,
  error_count integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hatsune_news_cron_runs_started_idx
  on public.hatsune_news_cron_runs(started_at desc);

alter table public.hatsune_news_cron_runs enable row level security;
revoke all on table public.hatsune_news_cron_runs from anon, authenticated;
