-- Track membership plan transitions so paid conversion can be measured accurately after launch.
create table if not exists public.bs_member_plan_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  from_plan text,
  to_plan text not null,
  changed_at timestamptz not null default now()
);

create index if not exists bs_member_plan_events_user_changed_idx
  on public.bs_member_plan_events(user_id, changed_at desc);

alter table public.bs_member_plan_events enable row level security;

revoke all on table public.bs_member_plan_events from anon, authenticated;
grant all on table public.bs_member_plan_events to service_role;

create or replace function public.bs_log_member_plan_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.bs_member_plan_events(user_id, from_plan, to_plan, changed_at)
    values (new.user_id, null, coalesce(new.plan, 'free'), coalesce(new.created_at, now()));
  elsif old.plan is distinct from new.plan then
    insert into public.bs_member_plan_events(user_id, from_plan, to_plan, changed_at)
    values (new.user_id, old.plan, coalesce(new.plan, 'free'), now());
  end if;
  return new;
end;
$$;

drop trigger if exists bs_member_plan_change_log on public.bs_member_profiles;
create trigger bs_member_plan_change_log
after insert or update of plan on public.bs_member_profiles
for each row execute function public.bs_log_member_plan_change();

insert into public.bs_member_plan_events(user_id, from_plan, to_plan, changed_at)
select p.user_id, null, coalesce(p.plan, 'free'), coalesce(p.created_at, now())
from public.bs_member_profiles p
where not exists (
  select 1 from public.bs_member_plan_events e where e.user_id = p.user_id
);
