create table if not exists public.bs_source_first_seen (
  id bigint generated by default as identity primary key,
  race_date date not null,
  course_code smallint not null,
  race_no smallint not null check (race_no between 1 and 12),
  data_kind text not null check (data_kind in ('exhibition','result','ai')),
  source text not null,
  first_seen_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  unique (race_date, course_code, race_no, data_kind, source)
);

create index if not exists bs_source_first_seen_date_kind_idx
  on public.bs_source_first_seen (race_date desc, data_kind, source);

alter table public.bs_source_first_seen enable row level security;

create or replace function public.bs_record_first_seen(
  p_race_date date,
  p_course_code smallint,
  p_race_no smallint,
  p_data_kind text,
  p_source text,
  p_seen_at timestamptz
) returns void
language plpgsql
set search_path = public
as $$
begin
  if p_race_date is null or p_course_code is null or p_race_no is null
     or p_data_kind is null or p_source is null or p_seen_at is null then
    return;
  end if;

  insert into public.bs_source_first_seen(
    race_date, course_code, race_no, data_kind, source, first_seen_at
  ) values (
    p_race_date, p_course_code, p_race_no, p_data_kind, p_source, p_seen_at
  )
  on conflict (race_date, course_code, race_no, data_kind, source)
  do update set first_seen_at = least(public.bs_source_first_seen.first_seen_at, excluded.first_seen_at);
end;
$$;

create or replace function public.bs_track_entry_first_seen()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.api_preview_synced_at is not null
     and (tg_op = 'INSERT' or old.api_preview_synced_at is distinct from new.api_preview_synced_at) then
    perform public.bs_record_first_seen(
      new.race_date,
      new.course_code,
      new.race_no,
      'exhibition',
      coalesce(nullif(new.api_preview_source,''), 'boatraceopenapi/v1'),
      new.api_preview_synced_at
    );
  end if;

  if new.exhibition_synced_at is not null
     and upper(coalesce(new.exhibition_source,'')) like '%PC-KYOTEI%'
     and (tg_op = 'INSERT' or old.exhibition_synced_at is distinct from new.exhibition_synced_at) then
    perform public.bs_record_first_seen(
      new.race_date,
      new.course_code,
      new.race_no,
      'exhibition',
      'PC-KYOTEI',
      new.exhibition_synced_at
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_bs_track_entry_first_seen on public.bs_race_entries;
create trigger trg_bs_track_entry_first_seen
after insert or update on public.bs_race_entries
for each row execute function public.bs_track_entry_first_seen();

create or replace function public.bs_track_result_first_seen()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.api_result_synced_at is not null
     and (tg_op = 'INSERT' or old.api_result_synced_at is distinct from new.api_result_synced_at) then
    perform public.bs_record_first_seen(
      new.race_date,
      new.course_code,
      new.race_no,
      'result',
      coalesce(nullif(new.api_result_source,''), 'boatraceopenapi/v1'),
      new.api_result_synced_at
    );
  end if;

  if new.synced_at is not null
     and new.api_result_synced_at is null
     and (tg_op = 'INSERT' or old.synced_at is distinct from new.synced_at) then
    perform public.bs_record_first_seen(
      new.race_date,
      new.course_code,
      new.race_no,
      'result',
      'PC-KYOTEI',
      new.synced_at
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_bs_track_result_first_seen on public.bs_race_results;
create trigger trg_bs_track_result_first_seen
after insert or update on public.bs_race_results
for each row execute function public.bs_track_result_first_seen();

create or replace function public.bs_track_ai_first_seen()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_seen_at timestamptz;
begin
  v_seen_at := coalesce(new.generated_at, new.predicted_at, new.created_at);
  if v_seen_at is not null and coalesce(new.timing,'') ilike '%live%' then
    perform public.bs_record_first_seen(
      new.race_date,
      new.course_code,
      new.race_no,
      'ai',
      coalesce(nullif(new.character_code,''), 'AI'),
      v_seen_at
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_bs_track_ai_first_seen on public.bs_ai_predictions;
create trigger trg_bs_track_ai_first_seen
after insert or update on public.bs_ai_predictions
for each row execute function public.bs_track_ai_first_seen();

create or replace view public.v_bs_source_speed_comparison
with (security_invoker = true)
as
with x as (
  select
    race_date,
    course_code,
    race_no,
    min(first_seen_at) filter (where data_kind='exhibition' and source='PC-KYOTEI') as pc_exhibition_at,
    min(first_seen_at) filter (where data_kind='exhibition' and source<>'PC-KYOTEI') as api_exhibition_at,
    min(first_seen_at) filter (where data_kind='result' and source='PC-KYOTEI') as pc_result_at,
    min(first_seen_at) filter (where data_kind='result' and source<>'PC-KYOTEI') as api_result_at,
    min(first_seen_at) filter (where data_kind='ai') as live_ai_at
  from public.bs_source_first_seen
  group by race_date, course_code, race_no
)
select
  *,
  extract(epoch from (pc_exhibition_at - api_exhibition_at))::numeric(12,3) as exhibition_pc_minus_api_seconds,
  case
    when api_exhibition_at is null or pc_exhibition_at is null then null
    when api_exhibition_at < pc_exhibition_at then 'API'
    when pc_exhibition_at < api_exhibition_at then 'PC-KYOTEI'
    else 'TIE'
  end as exhibition_winner,
  extract(epoch from (live_ai_at - least(api_exhibition_at, pc_exhibition_at)))::numeric(12,3) as exhibition_to_ai_seconds,
  extract(epoch from (pc_result_at - api_result_at))::numeric(12,3) as result_pc_minus_api_seconds,
  case
    when api_result_at is null or pc_result_at is null then null
    when api_result_at < pc_result_at then 'API'
    when pc_result_at < api_result_at then 'PC-KYOTEI'
    else 'TIE'
  end as result_winner
from x;
