create table if not exists public.bs_member_discord_links (
  user_id uuid primary key references auth.users(id) on delete cascade,
  discord_user_id text not null unique,
  discord_username text,
  discord_global_name text,
  discord_avatar text,
  linked_at timestamptz not null default now(),
  last_role_synced_at timestamptz,
  last_role_state text,
  updated_at timestamptz not null default now()
);

alter table public.bs_member_discord_links enable row level security;
revoke all on public.bs_member_discord_links from anon;
grant select on public.bs_member_discord_links to authenticated;
create policy "members can read own discord link"
on public.bs_member_discord_links for select
to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.bs_member_discord_oauth_states (
  state text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.bs_member_discord_oauth_states enable row level security;
revoke all on public.bs_member_discord_oauth_states from anon, authenticated;

create table if not exists public.bs_discord_notification_deliveries (
  id bigint generated by default as identity primary key,
  alert_type text not null,
  alert_id bigint not null,
  channel_key text not null,
  discord_message_id text,
  sent_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (alert_type, alert_id, channel_key)
);
alter table public.bs_discord_notification_deliveries enable row level security;
revoke all on public.bs_discord_notification_deliveries from anon, authenticated;

create index if not exists bs_member_discord_oauth_states_expiry_idx
  on public.bs_member_discord_oauth_states(expires_at);
create index if not exists bs_discord_notification_deliveries_lookup_idx
  on public.bs_discord_notification_deliveries(alert_type, alert_id, channel_key);
