create table if not exists public.bs_news_short_drafts (
  id bigint generated by default as identity primary key,
  short_date date not null unique,
  status text not null default 'draft' check (status in ('draft','approved','published')),
  character text not null default 'boatstrikers' check (character in ('ichika','hatsune','kiina','boatstrikers')),
  title text not null,
  hook text not null,
  narration text not null,
  selected_news jsonb not null default '[]'::jsonb,
  segments jsonb not null default '[]'::jsonb,
  captions jsonb not null default '[]'::jsonb,
  character_comment text,
  cta text not null default '詳しいニュースとデータはBoatStrikersで！',
  youtube_title text,
  description text,
  x_post text,
  hashtags text[] not null default array['#ボートレース','#競艇','#BoatStrikers']::text[],
  ai_model text,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bs_news_short_drafts enable row level security;

grant select, insert, update, delete on public.bs_news_short_drafts to service_role;
grant usage, select on sequence public.bs_news_short_drafts_id_seq to service_role;

create index if not exists bs_news_short_drafts_status_date_idx
  on public.bs_news_short_drafts(status, short_date desc);
