alter table public.bs_news_candidates
  add column if not exists event_date date,
  add column if not exists venue text,
  add column if not exists race_no integer,
  add column if not exists race_deadline timestamptz,
  add column if not exists event_type text,
  add column if not exists source_type text,
  add column if not exists verification_status text not null default 'pending',
  add column if not exists result_status text not null default 'unknown',
  add column if not exists verified boolean not null default false,
  add column if not exists verified_at timestamptz,
  add column if not exists verification_note text,
  add column if not exists verification_evidence jsonb not null default '{}'::jsonb,
  add column if not exists x_candidate boolean not null default false,
  add column if not exists x_character text,
  add column if not exists x_post_text text,
  add column if not exists x_hashtags text[] not null default '{}'::text[],
  add column if not exists x_status text not null default 'none';

do $$ begin
  alter table public.bs_news_candidates add constraint bs_news_candidates_verification_status_check check (verification_status in ('pending','verified','rejected'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.bs_news_candidates add constraint bs_news_candidates_result_status_check check (result_status in ('scheduled','running','confirmed','cancelled','unknown'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.bs_news_candidates add constraint bs_news_candidates_x_character_check check (x_character is null or x_character in ('ichika','hatsune','kiina','boatstrikers'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.bs_news_candidates add constraint bs_news_candidates_x_status_check check (x_status in ('none','draft','approved','posted','rejected'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.bs_news_candidates add constraint bs_news_candidates_race_no_check check (race_no is null or race_no between 1 and 12);
exception when duplicate_object then null; end $$;

create index if not exists bs_news_candidates_verification_idx on public.bs_news_candidates (verification_status, collected_at desc);
create index if not exists bs_news_candidates_x_status_idx on public.bs_news_candidates (x_status, collected_at desc);
create index if not exists bs_news_candidates_event_idx on public.bs_news_candidates (event_date, venue, race_no);

create table if not exists public.bs_news_sync_logs (
  id bigint generated by default as identity primary key,
  run_at timestamptz not null default now(),
  run_type text not null,
  source text,
  found_count integer not null default 0,
  verified_count integer not null default 0,
  rejected_count integer not null default 0,
  x_generated_count integer not null default 0,
  error_count integer not null default 0,
  details jsonb not null default '{}'::jsonb
);

create index if not exists bs_news_sync_logs_run_at_idx on public.bs_news_sync_logs (run_at desc);
