-- BoatStrikers AI v2 / Phase 1
-- New tables only. Existing prediction tables and production UI are not modified.

create table if not exists public.ai_v2_training_rows (
  race_date date not null,
  course_code smallint not null check (course_code between 1 and 24),
  race_no smallint not null check (race_no between 1 and 12),
  boat_no smallint not null check (boat_no between 1 and 6),
  data_timing text not null check (data_timing in ('previous_day','after_exhibition')),
  feature_version text not null default 'ai-v2-feature-v1',
  source_mode text not null default 'historical_reconstructed'
    check (source_mode in ('historical_reconstructed','prospective_snapshot')),
  captured_at timestamptz,

  race_day_no integer,
  is_female_race boolean,
  racer_class text,
  national_win_rate numeric,
  national_2_rate numeric,
  local_win_rate numeric,
  local_2_rate numeric,
  average_st numeric,
  motor_2_rate numeric,
  boat_2_rate numeric,
  flying_count integer,
  late_count integer,
  course1_average_st numeric,
  course1_top2_rate numeric,
  course1_race_count integer,

  relative_national numeric,
  relative_local numeric,
  relative_motor numeric,
  relative_st numeric,
  national_rank_in_race smallint,
  local_rank_in_race smallint,
  motor_rank_in_race smallint,
  st_rank_in_race smallint,

  exhibition_time numeric,
  exhibition_rank smallint,
  exhibition_st numeric,
  exhibition_course smallint,
  half_lap_time numeric,
  lap_time numeric,
  turn_time numeric,
  straight_time numeric,
  tilt numeric,
  wind_speed numeric,
  wave_height numeric,

  finish_position smallint,
  is_first boolean,
  is_second boolean,
  is_third boolean,
  ichika_target smallint check (ichika_target in (0,1)),
  hatsune_target smallint check (hatsune_target in (0,1)),
  kiina_target smallint check (kiina_target in (0,1)),

  feature_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  primary key (race_date, course_code, race_no, boat_no, data_timing)
);

create index if not exists ai_v2_training_rows_timing_date_idx
  on public.ai_v2_training_rows (data_timing, race_date);
create index if not exists ai_v2_training_rows_female_idx
  on public.ai_v2_training_rows (is_female_race, race_date);

create table if not exists public.ai_v2_models (
  id uuid primary key default gen_random_uuid(),
  model_name text not null,
  character_code text,
  prediction_target text not null,
  data_timing text not null check (data_timing in ('previous_day','after_exhibition')),
  model_type text not null,
  model_version text not null unique,
  feature_version text not null,
  training_start_date date not null,
  training_end_date date not null,
  training_race_count integer not null default 0,
  validation_start_date date,
  validation_end_date date,
  auc double precision,
  brier_score double precision,
  log_loss double precision,
  accuracy double precision,
  status text not null default 'candidate'
    check (status in ('candidate','active','archived','rejected')),
  is_active boolean not null default false,
  model_storage_path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);

create unique index if not exists ai_v2_models_one_active_target_idx
  on public.ai_v2_models (prediction_target, data_timing)
  where is_active = true;

create table if not exists public.ai_v2_predictions (
  id bigint generated by default as identity primary key,
  race_date date not null,
  course_code smallint not null check (course_code between 1 and 24),
  race_no smallint not null check (race_no between 1 and 12),
  boat_no smallint not null check (boat_no between 1 and 6),
  data_timing text not null check (data_timing in ('previous_day','after_exhibition')),
  model_version text not null,
  feature_version text not null,
  first_probability double precision,
  second_probability double precision,
  third_probability double precision,
  ichika_probability double precision,
  hatsune_probability double precision,
  kiina_probability double precision,
  feature_snapshot jsonb not null default '{}'::jsonb,
  explanation jsonb not null default '{}'::jsonb,
  predicted_at timestamptz not null default now(),
  unique (race_date, course_code, race_no, boat_no, data_timing, model_version)
);

create index if not exists ai_v2_predictions_lookup_idx
  on public.ai_v2_predictions (race_date, course_code, race_no, data_timing);

create table if not exists public.ai_v2_trifecta_predictions (
  id bigint generated by default as identity primary key,
  race_date date not null,
  course_code smallint not null check (course_code between 1 and 24),
  race_no smallint not null check (race_no between 1 and 12),
  data_timing text not null check (data_timing in ('previous_day','after_exhibition')),
  first_boat smallint not null check (first_boat between 1 and 6),
  second_boat smallint not null check (second_boat between 1 and 6),
  third_boat smallint not null check (third_boat between 1 and 6),
  combination text not null,
  probability double precision not null,
  probability_rank integer,
  odds double precision,
  expected_value double precision,
  model_version text not null,
  created_at timestamptz not null default now(),
  check (first_boat <> second_boat and first_boat <> third_boat and second_boat <> third_boat),
  unique (race_date, course_code, race_no, data_timing, combination, model_version)
);

create index if not exists ai_v2_trifecta_rank_idx
  on public.ai_v2_trifecta_predictions
  (race_date, course_code, race_no, data_timing, probability_rank);

create table if not exists public.ai_v2_daily_rankings (
  id bigint generated by default as identity primary key,
  ranking_date date not null,
  character_code text not null check (character_code in ('ichika','hatsune','kiina')),
  ranking_type text not null check (ranking_type in (
    'ichika_inside_best',
    'hatsune_inside_best',
    'hatsune_inside_danger',
    'kiina_boat5_best'
  )),
  rank_no integer not null,
  course_code smallint not null check (course_code between 1 and 24),
  race_no smallint not null check (race_no between 1 and 12),
  probability double precision not null,
  model_version text not null,
  summary text,
  metrics jsonb not null default '{}'::jsonb,
  selected_for_social boolean not null default false,
  selected_for_home boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (ranking_date, ranking_type, rank_no)
);

create index if not exists ai_v2_daily_rankings_date_idx
  on public.ai_v2_daily_rankings (ranking_date, ranking_type, rank_no);

create table if not exists public.ai_v2_model_evaluations (
  id bigint generated by default as identity primary key,
  model_version text not null,
  evaluation_start date not null,
  evaluation_end date not null,
  race_count integer not null default 0,
  auc double precision,
  brier_score double precision,
  log_loss double precision,
  top1_accuracy double precision,
  top3_accuracy double precision,
  trifecta_top1_hit_rate double precision,
  trifecta_top3_hit_rate double precision,
  trifecta_top5_hit_rate double precision,
  investment bigint,
  payout bigint,
  recovery_rate double precision,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.ai_v2_training_rows is
  'BoatStrikers AI v2 training features. previous_day rows must never contain exhibition/result-derived features.';
comment on column public.ai_v2_training_rows.source_mode is
  'historical_reconstructed may not exactly reproduce the original pre-race snapshot; prospective_snapshot is captured before the race.';
