
create table if not exists public.bs_race_data_quality_alerts (
  id bigint generated by default as identity primary key,
  race_date date not null,
  course_code smallint not null,
  course_name text,
  race_no smallint not null,
  severity text not null default 'warning'
    check (severity in ('warning','critical')),
  status text not null default 'active'
    check (status in ('active','resolved')),
  missing_fields text[] not null default '{}',
  detail jsonb not null default '{}'::jsonb,
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (race_date, course_code, race_no)
);

create index if not exists bs_race_data_quality_alerts_active_idx
  on public.bs_race_data_quality_alerts (status, race_date desc, course_code, race_no)
  where status = 'active';

alter table public.bs_race_data_quality_alerts enable row level security;
revoke all on table public.bs_race_data_quality_alerts from public, anon, authenticated;
grant all on table public.bs_race_data_quality_alerts to service_role;
grant all on sequence public.bs_race_data_quality_alerts_id_seq to service_role;

create or replace function public.bs_race_data_quality_rows(p_date date)
returns table (
  race_date date,
  course_code smallint,
  course_name text,
  race_no smallint,
  is_cancelled boolean,
  entry_rows bigint,
  exhibition_rows bigint,
  start_rows bigint,
  has_result boolean,
  has_payout boolean,
  missing_fields text[],
  is_complete boolean
)
language sql
security definer
set search_path = public
stable
as $$
  select
    e.race_date,
    e.course_code,
    max(e.course_name) as course_name,
    e.race_no,
    bool_or(e.race_cancel_code is not null) as is_cancelled,
    count(en.id) as entry_rows,
    count(en.id) filter (
      where coalesce(en.official_exhibition_time,en.exhibition_time) is not null
    ) as exhibition_rows,
    count(en.id) filter (
      where coalesce(en.actual_start_timing,en.actual_st) is not null
    ) as start_rows,
    coalesce(bool_or(r.id is not null),false) as has_result,
    coalesce(bool_or(
      r.id is not null
      and r.trifecta_payout is not null
      and coalesce(r.trifecta_result,r.winning_trifecta) is not null
    ),false) as has_payout,
    case when bool_or(e.race_cancel_code is not null) then '{}'::text[]
      else array_remove(array[
        case when count(en.id) <> 6 then 'entries' end,
        case when count(en.id) filter (
          where coalesce(en.official_exhibition_time,en.exhibition_time) is not null
        ) <> 6 then 'exhibition' end,
        case when not coalesce(bool_or(r.id is not null),false) then 'result' end,
        case when not coalesce(bool_or(
          r.id is not null
          and r.trifecta_payout is not null
          and coalesce(r.trifecta_result,r.winning_trifecta) is not null
        ),false) then 'payout' end,
        case when count(en.id) filter (
          where coalesce(en.actual_start_timing,en.actual_st) is not null
        ) <> 6 then 'result_detail' end
      ],null)
    end as missing_fields,
    bool_or(e.race_cancel_code is not null) or (
      count(en.id) = 6
      and count(en.id) filter (
        where coalesce(en.official_exhibition_time,en.exhibition_time) is not null
      ) = 6
      and coalesce(bool_or(
        r.id is not null
        and r.trifecta_payout is not null
        and coalesce(r.trifecta_result,r.winning_trifecta) is not null
      ),false)
      and count(en.id) filter (
        where coalesce(en.actual_start_timing,en.actual_st) is not null
      ) = 6
    ) as is_complete
  from public.bs_race_events e
  left join public.bs_race_entries en
    using (race_date,course_code,race_no)
  left join public.bs_race_results r
    using (race_date,course_code,race_no)
  where e.race_date = p_date
  group by e.race_date,e.course_code,e.race_no
$$;

revoke all on function public.bs_race_data_quality_rows(date) from public, anon, authenticated;
grant execute on function public.bs_race_data_quality_rows(date) to postgres, service_role;

create or replace function public.bs_race_data_completeness(p_date date)
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
with quality as (
  select * from public.bs_race_data_quality_rows(p_date)
),
summary as (
  select
    count(*) as races,
    count(*) filter (where is_cancelled or entry_rows=6) as entries_complete,
    count(*) filter (where is_cancelled or exhibition_rows=6) as exhibition_complete,
    count(*) filter (where is_cancelled or (has_result and has_payout)) as results_complete,
    count(*) filter (where is_cancelled or (has_result and start_rows=6)) as result_details_complete,
    count(*) filter (where not is_complete) as issue_count,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'race_date',race_date,
          'course_code',course_code,
          'course_name',course_name,
          'race_no',race_no,
          'missing_fields',missing_fields,
          'entry_rows',entry_rows,
          'exhibition_rows',exhibition_rows,
          'start_rows',start_rows,
          'has_result',has_result,
          'has_payout',has_payout
        )
        order by course_code,race_no
      ) filter (where not is_complete),
      '[]'::jsonb
    ) as issues
  from quality
)
select jsonb_build_object(
  'race_date',p_date,
  'races',races,
  'entries_complete',entries_complete,
  'exhibition_complete',exhibition_complete,
  'results_complete',results_complete,
  'result_details_complete',result_details_complete,
  'issue_count',issue_count,
  'issues',issues,
  'is_complete',(races > 0 and issue_count=0),
  'checked_at',now()
)
from summary
$$;

revoke all on function public.bs_race_data_completeness(date) from public, anon, authenticated;
grant execute on function public.bs_race_data_completeness(date) to postgres, service_role;

create or replace function public.bs_record_race_data_completeness(p_date date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_detail jsonb;
  v_status text;
  v_active integer := 0;
  v_resolved integer := 0;
begin
  if p_date is null
     or p_date > (now() at time zone 'Asia/Tokyo')::date
     or p_date < date '2024-01-01' then
    raise exception 'invalid completeness date';
  end if;

  v_detail := public.bs_race_data_completeness(p_date);
  v_status := case when coalesce((v_detail->>'is_complete')::boolean,false)
    then 'success' else 'partial' end;

  insert into public.bs_race_data_quality_alerts (
    race_date,course_code,course_name,race_no,severity,status,
    missing_fields,detail,first_detected_at,last_detected_at,resolved_at,updated_at
  )
  select
    q.race_date,q.course_code,q.course_name,q.race_no,
    case when 'entries'=any(q.missing_fields) or 'result'=any(q.missing_fields)
      then 'critical' else 'warning' end,
    'active',q.missing_fields,
    jsonb_build_object(
      'entry_rows',q.entry_rows,
      'exhibition_rows',q.exhibition_rows,
      'start_rows',q.start_rows,
      'has_result',q.has_result,
      'has_payout',q.has_payout,
      'checked_at',now()
    ),
    now(),now(),null,now()
  from public.bs_race_data_quality_rows(p_date) q
  where not q.is_complete
  on conflict (race_date,course_code,race_no) do update set
    course_name=excluded.course_name,
    severity=excluded.severity,
    status='active',
    missing_fields=excluded.missing_fields,
    detail=excluded.detail,
    last_detected_at=now(),
    resolved_at=null,
    updated_at=now();

  get diagnostics v_active = row_count;

  update public.bs_race_data_quality_alerts a
  set status='resolved',resolved_at=now(),updated_at=now()
  where a.race_date=p_date
    and a.status='active'
    and not exists (
      select 1
      from public.bs_race_data_quality_rows(p_date) q
      where q.course_code=a.course_code
        and q.race_no=a.race_no
        and not q.is_complete
    );

  get diagnostics v_resolved = row_count;

  insert into public.bs_live_source_sync_logs(
    source,sync_kind,race_date,status,
    entry_rows,event_rows,result_rows,result_entry_rows,
    started_at,finished_at,detail
  )
  values (
    'boatstrikers/completeness-v2','daily_completeness',p_date,v_status,
    (v_detail->>'entries_complete')::integer,
    (v_detail->>'races')::integer,
    (v_detail->>'results_complete')::integer,
    (v_detail->>'result_details_complete')::integer,
    now(),now(),
    v_detail || jsonb_build_object(
      'active_alerts_written',v_active,
      'alerts_resolved',v_resolved,
      'notification_target','admin_alert_center'
    )
  );

  if v_status='partial' then
    perform pg_notify(
      'boatstrikers_data_quality_alert',
      jsonb_build_object(
        'race_date',p_date,
        'issue_count',(v_detail->>'issue_count')::integer,
        'checked_at',now()
      )::text
    );
  end if;

  return v_detail || jsonb_build_object(
    'active_alerts_written',v_active,
    'alerts_resolved',v_resolved
  );
end
$$;

revoke all on function public.bs_record_race_data_completeness(date) from public, anon, authenticated;
grant execute on function public.bs_record_race_data_completeness(date) to postgres, service_role;
